### ISSUE TITLE
index vs index! problems with wildcard permission API keys

### ISSUE THREAD

**Issue by vincentwoo** [algolia/algoliasearch-rails#100]
If you have an API key set to something like *_development (which is encouraged by the `algoliasearch-rails` convention of `algoliasearch per_environment: true do`), you will run into problems trying to do

`Model.reindex`

vs

`Model.reindex!`.

The latter works fine because it's in place, but the former will fail because it tries to an index named something like `Model_development.tmp` which it does not have access to because the index name does not end in `_development` anymore. This is a bit nonintuitive.

**Comment by redox** [comment]
Good point @vincentwoo, I'm gonna add a note in the README about that.
