### ISSUE TITLE
README enqueuing instructions are... a bit confusing

### ISSUE THREAD

**Issue by vincentwoo** [algolia/algoliasearch-rails#102]
For example, read the snippet for explaining how to trigger sidekiq queueing:

```ruby
class Contact < ActiveRecord::Base
  include AlgoliaSearch

  algoliasearch enqueue: :trigger_sidekiq_worker do
    attribute :first_name, :last_name, :email
  end

  def self.trigger_sidekiq_worker(record, remove)
    MySidekiqWorker.perform_async(record.id, remove)
  end
end

class MySidekiqWorker
  def perform(id, remove)
    c = Contact.find(id)
    remove ? c.remove_from_index! : c.index!
  end
end
```

If a record is deleted, presumably the worker will be enqueued with the tuple `id`, `true`. At some later point, the worker will attempt to run `Contact.find id` and immediately throw an exception because that id will not be present in the table. Even if it didn't, somehow, what would be returned? Probably `nil`, since the record is gone. How then can you call `remove_from_index!` on `c`?

**Comment by vincentwoo** [comment]
As an aside, I know you have a more complete example above that handles deleting better, mostly I am confused as to why a sidekiq example that could never work is included.

There should also probably be a helper to get the computed Algolia index name from the model class!

**Comment by vincentwoo** [comment]
Found it!

This might be a better snippet for a general algolia worker:

```ruby
  # don't actually need removed parameter here, now
  def self.trigger_algolia_update record, removed
    AlgoliaSyncWorker.perform_async Contact, record.id
  end
```

```ruby
class AlgoliaSyncWorker
    include Sidekiq::Worker

  def perform klass, id
    record = klass.find_by_id id
    if record
      record.index!
    else
      Algolia::Index.new(klass.index_name).delete_object(id)
    end
  end
end
```

**Comment by redox** [comment]
Yes OK, that makes sense. Do you want to submit a PR @vincentwoo?

**Comment by vincentwoo** [comment]
no

**Comment by redox** [comment]
We'll tackle it while fixing #75
