### ISSUE TITLE
Kaminari pagination with `raw_search`

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-rails#104]
Currently, we cannot paginate the result of a call to `raw_search` with Kaminari. It is only possible with the `search` method.

It results in a `undefined method 'total_pages'` error due to the fact that `raw_search` and `search` do not have the same kind of return value.

**Comment by redox** [comment]
Unfortunately if you go for the `raw_search` method, you'll need to deal with the Kaminari-wrapper allowing pagination yourself; this is not something the gem will provide OOTB.
