### ISSUE TITLE
Might have missed it; rails5 support ?

### ISSUE THREAD

**Issue by bbnnt** [algolia/algoliasearch-rails#107]
Wondering how to configure it using rails5.

algoliasearch.rb in config/initializers returns `uninitialized constant AlgoliaSearch`and adding the scripts to application.js returnrs the following `couldn't find file 'algolia/v3/algoliasearch.min' with type 'application/javascript'`

**Comment by redox** [comment]
Yep, didn't test it yet with Rails 5 but we could definitely start investigating because I don't expect a lot of migration issues. The only thing I'm not happy with is the way we test it on Travis-ci -> we really need to find a way to test all versions of Rails.

Since you have a setup @bbnnt, any chance you would like to try a PR?

**Comment by vincentwoo** [comment]
It's been a few months, please update us on the situation, @redox.

**Comment by redox** [comment]
> It's been a few months, please update us on the situation, @redox.

I'm happy to merge any PR if you guys have time and want to move forward; didn't take the time on my side do deal with it.

**Comment by vincentwoo** [comment]
Are you going to? We, uh, pay you money for Algolia, and rails 5 support seems entirely reasonable to expect from aloliasearch-rails.

**Comment by alexandremeunier** [comment]
@vincentwoo Yes absolutely. Rails 5 was officially released but a week ago and we haven't had the time to look at it as @redox mentioned, but I'm going to have a look today.

**Comment by alexandremeunier** [comment]
I have run a few tests and everything seems to be working fine. The gem specs are passing, and the gem/modules are loading correctly in a fresh rails 5 application.

@bbnnt are you still running into those issues ?

@vincentwoo did you run into any particular issues ?

**Comment by vincentwoo** [comment]
I haven't tried it yet. I'm scoping out all my dependencies for compatibility. If you think you're Rails 5 ready, it would be cool if you updated the README. You should also probably have different Rails versions as part of your (currently failing) test matrix: https://travis-ci.org/algolia/algoliasearch-rails/builds/142288497.

**Comment by dkoprov** [comment]
Specs are green, our own rails 5 project has not any issues with the gem.
It appears, this issue can be closed, does it?

**Comment by redox** [comment]
> Specs are green, our own rails 5 project has not any issues with the gem.
> It appears, this issue can be closed, does it?

Oh yes yes, it has been tested & validated. Forgot to close!
