### ISSUE TITLE
Sidekiq queuing too fast

### ISSUE THREAD

**Issue by cmalpeli** [algolia/algoliasearch-rails#110]
You may want to consider update the docs for Sidekiq to use something like:

`MySidekiqWorker.perform_in(5.seconds, record.id, remove)`

Sidekiq can be so fast that sometimes the record won't existing in the DB at the time of execution.  [See here for details.](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#cannot-find-modelname-with-id12345)

I saw this in production and solved with the above

**Comment by redox** [comment]
Definitely. Need to fix #75.
