### ISSUE TITLE
multiple_queries support?

### ISSUE THREAD

**Issue by robertjwhitney** [algolia/algoliasearch-rails#113]
From what I can gather from documentation, and not finding anything in the source, the gem does not support multiple category queries a la https://www.algolia.com/doc/ruby#multiple-queries ?

**Comment by redox** [comment]
> From what I can gather from documentation, and not finding anything in the source, the gem does not support multiple category queries a la https://www.algolia.com/doc/ruby#multiple-queries ?

Indeed this is not exposed in the Rails integration but you can use the underlying Ruby API client singleton so you can query the [`multi_queries`](https://github.com/algolia/algoliasearch-client-ruby#multiple-queries) method as described in the doc you're mentioning.

**Comment by robertjwhitney** [comment]
Yeah- just supporting a bunch of legacy code, so i'm trying to do a backend-search implementation for the moment, and unfortunately, the Ruby API client lacks the handy mapping to instances of my resource. Would you accept a pull for this?

**Comment by robertjwhitney** [comment]
Actually I guess I'll just bite the bullet.
