### ISSUE TITLE
Is there a way of getting the total count of records (when using pagination)?

### ISSUE THREAD

**Issue by Ricardonacif** [algolia/algoliasearch-rails#115]
Hey guys, is there a way of getting the total count of records (when using pagination)?

**Comment by redox** [comment]
Hi @Ricardonacif,

yes there is. You can use the `algolia_raw_answer` (or the aliased `raw_answer`) method to get access to the raw JSON answer + `nbHits` attributes.

```ruby
res = MyModel.search 'foo'
p res.raw_answer['nbHits']
```

The source code [here](https://github.com/algolia/algoliasearch-rails/blob/master/lib/algoliasearch-rails.rb#L585) and [here](https://github.com/algolia/algoliasearch-rails/blob/master/lib/algoliasearch-rails.rb#L535-L555).

**Comment by Ricardonacif** [comment]
Thanx @redox !
