### ISSUE TITLE
Reindex on model runs but does not update Algolia index

### ISSUE THREAD

**Issue by rutgerg** [algolia/algoliasearch-rails#117]
If I reindex my model by running: Model.reindex from console I see process is running. On Algolia tmp index is made but tmp index does not show docs. Since tmp stays empty and is copied to index after finish of reindex main index is empty.

If I loop over records or run Model.first.index Algolia index is updated. So algoliasearch is set up correctly in my model it seems. Not sure how to debug any further.

I'm on 1.14.1. Any suggestion?

**Comment by redox** [comment]
Do you have any `:if`/`:unless` constraints option configured? I expect it's somehow around that.

> If I loop over records or run Model.first.index Algolia index is updated. So algoliasearch is set up correctly in my model it seems. Not sure how to debug any further.

Running `.index` manually will bypass that so it's expected to have something in the index in the 2nd case.

**Comment by rutgerg** [comment]
I don't have an :if option set but do have id:, index_name: and per_environment: options in place

**Comment by redox** [comment]
> I don't have an :if option set but do have id:, index_name: and per_environment: options in place

Any chance you could copy/paste your `algoliasearch` block so we can better understand?

**Comment by rutgerg** [comment]
Arrgh, I eliminated all (added) attributes one by one to see which caused the problem. I found out I used 'lon' in stead of 'lng' for geoloc. That caused the problem.

**Comment by redox** [comment]
> Arrgh, I eliminated all (added) attributes one by one to see which caused the problem. I found out I used 'lon' in stead of 'lng' for geoloc. That caused the problem.

Ahah, that's fine :) I'm glad we understood that issue 👍 

Let us know how it goes :)
