### ISSUE TITLE
Builds failing

### ISSUE THREAD

**Issue by nysthee** [algolia/algoliasearch-rails#122]
Looks like all builds are failing on Travis.

**Comment by Jerskouille** [comment]
Hi @nysthee , thanks for reporting this. We're aware of it, and we're currently adapting our test suite to execute with a more complete ruby/rails matrix. We are waiting to make everything green before releasing a new version. Right now, the most important ones for us (ruby 2.3 w/ rails 4&5) are passing.

**Comment by nysthee** [comment]
Hi @Jerskouille 

Not sure if I am looking on the wrong place but the Travis report I see is all red.

![screenshot 2016-07-27 11 34 42](https://cloud.githubusercontent.com/assets/11569296/17170832/2faf2838-53ee-11e6-93ed-8ab4623c8b0b.png)

**Comment by Jerskouille** [comment]
Oh indeed, on your pull request, I thought it was disabled. Our test suite needs access to secure environment variables `ALGOLIA_APPLICATION_ID` and `ALGOLIA_API_KEY`, and we can't expose this to Pull Requests. I've disabled travis builds on PRs.
The run you should look at is the resulting build of the merge [n°275](https://travis-ci.org/algolia/algoliasearch-rails/builds/147687802) .

**Comment by nysthee** [comment]
Ok thanks for the info. Just out of curiosity, why is this a security issue? And how is this configured? Because I can't see any of this in the travis config.

**Comment by Jerskouille** [comment]
Well, the test suite needs a write API key to an Algolia application which we don't want to share.
We're setting these environment variables directly in the [`.travis.yml` file](https://github.com/algolia/algoliasearch-rails/blob/master/.travis.yml#L43-L45).

**Comment by nysthee** [comment]
Ok I understand that. But I dont't understand the security issue as the keys are encrypted. Also how do you expose them on a context base? (only for commits tot master?)

**Comment by Jerskouille** [comment]
Because they're encrypted until they're used in the test-suite. Change a test file to `puts ENV['ALGOLIA_API_KEY']` in your pull request, and the variable would be showing up.
You can get more info about this here: https://blog.travis-ci.com/2013-06-10-secure-env-in-pull-requests/ .

**Comment by nysthee** [comment]
Ok thx for the information?
