### ISSUE TITLE
Product.reindex! doesn't create products on Algolia, Rails 3.0.3 ruby 1.8.7

### ISSUE THREAD

**Issue by carltonjr** [algolia/algoliasearch-rails#123]
I'm running Product.reindex! on Dev rails environment, but nothing is being created on Algolia's end. No error messages are displayed in the console. I can see a few POST requests hitting algolia via the dashboard, but no product information is being sent with the request. I'm on Rails 3.0.3 and Ruby 1.8.7

My Product model has the following: 

  include AlgoliaSearch

  algoliasearch :per_environment => true do
    # all attributes will be sent
    attributes :name
  end

and I've created the Algolia index for "Product_development"

**Comment by redox** [comment]
That's weird @carltonjr; what kind of POST requests are you seeing? If you click on the logs in your dashboard you'll see the underlying API calls -> that's definitely the best way to understand what is going on.

Are you using ActiveRecord, Sequel or MongoDB ?

**Comment by carltonjr** [comment]
Hi @redox, I'm seeing these requests on the Algolia Dashboard when I run reindex. 

GET
/1/indexes/Product_development/settings?getVersion=2
POST
/1/indexes/Product_development/query
{
  "params": "query=&getRankingInfo=1&facets=*&attributesToRetrieve=*&highlightPreTag=%3Cem%3E&highlightPostTag=%3C%2Fem%3E&hitsPerPage=10&facetFilters=%5B%5D&maxValuesPerFacet=100"
}
POST
/1/indexes/Product_development/query
{
  "params": "query=&hitsPerPage=10&attributesToRetrieve=*&distinct=false"
}
GET
/1/indexes?page=0

**Comment by carltonjr** [comment]
Actually it seems those requests are coming from simply hitting the indices tab. Looks like running reindex doesn't send any requests to Algolia. Nor does clear_index!

**Comment by redox** [comment]
> Actually it seems those requests are coming from simply hitting the indices tab. Looks like running reindex doesn't send any requests to Algolia. Nor does clear_index!

Hmmm, can you double-check you're using the correct APPLICATION_ID & also that you didn't enable any mocking mechanism? Even if we don't send any object, the gem should at least create the index.

**Comment by carltonjr** [comment]
Thanks I've double checked the ApplicationID and that it's using the AdminAPI key. No index is being created and it doesn't seem any requests are being sent to Algolia. 

`1.8.7-head :001 > Product.reindex
  SQL (0.4ms)  SHOW client_min_messages
  SQL (0.2ms)  SET client_min_messages TO 'panic'
  SQL (0.2ms)  SET standard_conforming_strings = on
  SQL (0.1ms)  SET client_min_messages TO 'notice'
  SQL (0.3ms)  SET time zone 'UTC'
  SQL (0.1ms)  SHOW TIME ZONE
Scoped order and limit are ignored, it's forced to be batch order and batch size
  SQL (3.5ms)   SELECT tablename
 FROM pg_tables
 WHERE schemaname = ANY (current_schemas(false))

  SQL (2.5ms)   SELECT a.attname, format_type(a.atttypid, a.atttypmod), d.adsrc, a.attnotnull
 FROM pg_attribute a LEFT JOIN pg_attrdef d
 ON a.attrelid = d.adrelid AND a.attnum = d.adnum
 WHERE a.attrelid = '"products"'::regclass
 AND a.attnum > 0 AND NOT a.attisdropped
 ORDER BY a.attnum

  Product Load (6.4ms)  SELECT "products".* FROM "products" WHERE ("products"."id" >= 0) ORDER BY products.id ASC LIMIT 1000
  SQL (1.2ms)   SELECT a.attname, format_type(a.atttypid, a.atttypmod), d.adsrc, a.attnotnull
 FROM pg_attribute a LEFT JOIN pg_attrdef d
 ON a.attrelid = d.adrelid AND a.attnum = d.adnum
 WHERE a.attrelid = '"products"'::regclass
 AND a.attnum > 0 AND NOT a.attisdropped
 ORDER BY a.attnum

  Product Load (5.2ms)  SELECT "products".* FROM "products" WHERE ("products"."id" > 11566) ORDER BY products.id ASC LIMIT 1000
  Product Load (5.0ms)  SELECT "products".* FROM "products" WHERE ("products"."id" > 12566) ORDER BY products.id ASC LIMIT 1000
  Product Load (5.2ms)  SELECT "products".* FROM "products" WHERE ("products"."id" > 13567) ORDER BY products.id ASC LIMIT 1000
  Product Load (5.5ms)  SELECT "products".* FROM "products" WHERE ("products"."id" > 14567) ORDER BY products.id ASC LIMIT 1000
  Product Load (3.3ms)  SELECT "products".* FROM "products" WHERE ("products"."id" > 18205) ORDER BY products.id ASC LIMIT 1000
 => nil 
1.8.7-head :002 > 
`

**Comment by redox** [comment]
> Thanks I've double checked the ApplicationID and that it's using the AdminAPI key. No index is being created and it doesn't seem any requests are being sent to Algolia.

That's so weird :/ And you confirm you don't have any `disable_indexing` option or any `:if` and `:unless` constraints on the `algoliasearch` block, right?

**Comment by carltonjr** [comment]
Yes none of those options just:   

algoliasearch :per_environment => true do
  attributes :name
end

We don't have any tests on this app, so it's unlikely to be anything specific to our app, but perhaps a mocking mechanism of another gem is causing a conflict?

**Comment by carltonjr** [comment]
I went ahead and just upgraded the app to Rails 4. Had been meaning to do it for a while anyways. Everything is working now.

**Comment by redox** [comment]
> [algoliasearch-rails] Cannot reach any host: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure

Ah ok, this one is interesting. Looks like you were still depending on a SSLv3-compliant library or something like that. For sure that was the root cause.

> I went ahead and just upgraded the app to Rails 4. Had been meaning to do it for a while anyways. Everything is working now.

Alright, that's good to know! Happy coding then :)
