### ISSUE TITLE
cannot POST to algolia.net with rails & more doc's on istantsearch.js for rails.. please

### ISSUE THREAD

**Issue by SupaaDG** [algolia/algoliasearch-rails#124]
every time i try and add a record from rails console i get this 

[algoliasearch-rails] Cannot POST to https://*******.algolia.net/1/indexes/Place/batch: {"message":"Invalid Application-ID or API key","status":403}
 (403)
=> nil

but when i check my env.. its correct. both to the app_id and admin_api_key are correct!!
please help 
-also the front-end documentation on how to incorporate rails with instantsearch.js is extremely vague.. it seems it would only work with node.js, and as a beginner in ROR id like to incorporate Algolia live search without templeting from a node.js example.. please help.

**Comment by redox** [comment]
Hi @SupaaDG,

> but when i check my env.. its correct. both to the app_id and admin_api_key are correct!! please help 

the best way to debug such 403 issue is to check (from our algolia.com web dashboard) the calls we're receiving. Inspect the error logs there, you should be able to confirm that the good API keys is the good one.

> -also the front-end documentation on how to incorporate rails with instantsearch.js is extremely vague.. it seems it would only work with node.js, and as a beginner in ROR id like to incorporate Algolia live search without templeting from a node.js example.. please help.

No need to use Node.js but indeed you'll need to use our JavaScript libraries. I recommend you to follow those tutorials:
 - https://www.algolia.com/doc/guides/search/auto-complete
 - https://www.algolia.com/doc/guides/search/instant-search

Let us know how that goes 👍 

PS: I'm closing the issue for now, feel free to re-open.

**Comment by SupaaDG** [comment]
When i look at the env i have it as ALGOLIASEARCH_APPLICATION_ID not X-Algolia-API-Key like it shows in the header. should my env file look like  X-Algolia-Application-Id and X-Algolia-API-Key:

**Comment by redox** [comment]
> When i look at the env i have it as ALGOLIASEARCH_APPLICATION_ID not X-Algolia-API-Key like it shows in the header. should my env file look like X-Algolia-Application-Id and X-Algolia-API-Key:

Yes definitely. Are you a Heroku user? I know we've been experiencing some issues lately setting the API KEY env variable :/
