### ISSUE TITLE
numerics in database sent as strings

### ISSUE THREAD

**Issue by joevandyk** [algolia/algoliasearch-rails#125]
Hi,

Is there a way to automatically send numerics (in a postgresql database, Ruby represents them as BigDecimals) as floats to algolia instead of strings?

Thanks!

**Comment by redox** [comment]
Hey @joevandyk,

yes, that looks a limitation of [ActiveRecord + BigDecimal + JSON](http://stackoverflow.com/questions/6128794/rails-json-serialization-of-decimal-adds-quotes).

I recommend you to do something like:

```ruby
algoliasearch do
  attribute :my_attr do
    # convert BigDecimal to Float to work-around JSON serialization
    my_attr.to_f
  end
end
```

Let me know if that works for you 👍

**Comment by joevandyk** [comment]
I'm just going with 
```
# Otherwise Rails encodes numerics as Strings which is a little confusing.
class BigDecimal
  def as_json(options = nil)
    to_f
  end
end
```
cuz all our data are like `32.23` -- rounding shouldn't be an issue.

**Comment by redox** [comment]
Sure, that is another option 👍 

I'm closing this issue then :)

**Comment by pimpin** [comment]
I cannot figure a way to force float precision in case of `0` digits.
Ive tried
```ruby
algoliasearch do
  attribute :my_attr do
    # convert BigDecimal to Float to work-around JSON serialization
    sprintf( "%0.02f", my_attr.to_f)
  end
end
```
but we loose any lasting 0 in float after separator/
Any idea please?
