### ISSUE TITLE
Missing documentation for initial indexing

### ISSUE THREAD

**Issue by whitmanc** [algolia/algoliasearch-rails#126]
First of all, thanks for the great gem. I wanted to point out that the documentation explains how to re-index a model, but not how to index one initially (with `index` function instead of `reindex` on a modal). Running `reindex` when an index doesn't exist will result in an error. Or, maybe something went right over my head =P

https://github.com/algolia/algoliasearch-rails#indexing

I can open a PR if you guys want.

**Comment by redox** [comment]
> First of all, thanks for the great gem.

Very come, thanks for the positive feedback :+1:

> Running reindex when an index doesn't exist will result in an error. Or, maybe something went right over my head =P

Arg the `reindex` method should work :/ Any chance what you see is a 404 error, logged in the console? I fixed it a few weeks ago (only a log actually, everything goes well) but we didn't release any version since then (it should be done very soon but we have issues with rubinius /o\).

You can maybe try the `master` branch in the meantime?

Anyway any PR improving the README is welcome 👍

**Comment by whitmanc** [comment]
@redox Thanks for the prompt response! It is indeed a 404, here are my console logs (should have provided this in the first place, d'oh!): 

```
irb(main):002:0> Post.reindex
[algoliasearch-rails] Cannot GET to https://9XVKRD3ZTC-dsn.algolia.net/1/indexes/Post/settings: {"message":"Index does not exist","status":404} (404)
[algoliasearch-rails] Cannot GET to https://9XVKRD3ZTC-dsn.algolia.net/1/indexes/Post/settings: {"message":"Index does not exist","status":404} (404)
[algoliasearch-rails] Cannot GET to https://9XVKRD3ZTC-dsn.algolia.net/1/indexes/Post.tmp/settings: {"message":"Index does not exist","status":404} (404)
[algoliasearch-rails] Cannot PUT to https://9XVKRD3ZTC.algolia.net/1/indexes/Post.tmp/settings: {"message":"Invalid object attributes: error near line:1 column:8","status":400}
 (400)
```

If it works on `master`, I assume that README updating wouldn't be necessary, since it would be resolved in a near-future release. I'll follow up after trying from `master` - will squeeze it in first thing tomorrow AM. Need to index another environment anyways, so it's convenient.

**Comment by redox** [comment]
> If it works on master, I assume that README updating wouldn't be necessary, since it would be resolved in a presumably near-future release. I'll follow up after trying from master - will squeeze it in first thing tomorrow AM. Need to index another environment anyways, so it's convenient.

Makes sense 👍 I'll close this issue in the meantime then 💯
