### ISSUE TITLE
Disable Tolerance on Specific Search

### ISSUE THREAD

**Issue by Brotakuu** [algolia/algoliasearch-rails#128]
How can I disable tolerance on a specific search?

    p Deal.raw_search("LG 29in", {:disableTypoToleranceOn => true})
    [algoliasearch-rails] Cannot POST to https://xxx.algolia.net/1/indexes/Deal/query: {"message":"Unknown parameter: disableTypoToleranceOn","status":400}
 (400)

**Comment by Brotakuu** [comment]
Found it

    Deal.search("LG 29in", typoTolerance: false)

**Comment by redox** [comment]
Hi @Brotakuu; yes that's it 👍
