### ISSUE TITLE
How to add a numeric filter to search query

### ISSUE THREAD

**Issue by Brotakuu** [algolia/algoliasearch-rails#129]
Is it possible to add a numeric filter to the search query? Such as `price > 0`.

    @deals = Deal.search(@query, typoTolerance: false)

**Comment by redox** [comment]
> Is it possible to add a numeric filter to the search query? Such as price > 0.

Oh yeah sure, just do:

```
@deals = Deal.search(@query, typoTolerance: false, numericFilters: ['price>0'])
```

Closing the issue, feel free to re-open 👍
