### ISSUE TITLE
Index settings: typoTolerance

### ISSUE THREAD

**Issue by yogodoshi** [algolia/algoliasearch-rails#135]
Maybe I'm confusing something but, on this project readme there is a link to the [ruby client index settings parameters](https://github.com/algolia/algoliasearch-client-ruby/tree/1.11.0#index-settings-parameters) and there I found an option named `typoTolerance` but when I tried setting it inside `algoliasearch` block I got the error:

```
NoMethodError: undefined method `typoTolerance' for #<AlgoliaSearch::IndexSettings:0x007fc17fa2f5b0>
```

After some digging I found [here](https://github.com/algolia/algoliasearch-rails/blob/4f8bcafbd1e0806bc383d1aa3957f436f9e65bfa/lib/algoliasearch-rails.rb#L65) that the option seem to be renamed to `disableTypoToleranceOnWords`, dont know the reason but I think it should at least be mentioned on this project's readme cause right now by linking to the ruby client readme, it looks like every option there should also work here. #my2cents

**Comment by redox** [comment]
Good catch @yogodoshi 👍

**Comment by redox** [comment]
> After some digging I found here that the option seem to be renamed to disableTypoToleranceOnWords, dont know the reason but I think it should at least be mentioned on this project's readme cause right now by linking to the ruby client readme, it looks like every option there should also work here. #my2cents

No no, it was really missing. `disableTypoToleranceOnWords` is another option to only disable typo-tolerance on specific words.
