### ISSUE TITLE
Facet search return NoMethodError

### ISSUE THREAD

**Issue by Maryskr** [algolia/algoliasearch-rails#136]
Hi there!
I would like to set up algolia for search for my ror application.
When i try to use facet search, i've got an error about undefined method at your lib.
`ModelName.algolia_search_facet('categoty_ids', 'N')
NoMethodError: undefined method `search_facet' for #<AlgoliaSearch::SafeIndex:0x007f862a4a0cd8>
	from /path_to_project/vendor/bundle/ruby/2.3.0/bundler/gems/algoliasearch-rails-349fff217924/lib/algoliasearch-rails.rb:646:in `algolia_search_facet'
`

**Comment by redox** [comment]
Hi @Maryskr,

oh this new feature is not yet exposed in our rails wrapper. I'm gonna check if this is something I can release now.

**Comment by redox** [comment]
Hi @Maryskr,

Sorry about that, this is because the underlying `algoliasearch` gem is not updated (1.12.0 required). I'm gonna release a new version of the `algoliasearch-rails` gem and force the underlying one to be updated.

**Comment by redox** [comment]
Hu @Maryskr, this has been released in `1.16.3`; updating there should fix the issue :)

Also, the new name (we kept the old one for backward compat) is `search_for_facet_values(...)`.
