### ISSUE TITLE
browse method only accepts page and hitsPerPage

### ISSUE THREAD

**Issue by brokenfingers** [algolia/algoliasearch-rails#139]
Why does `browse` method for rails integration does not accept anything else other than `page` and `hitsPerPage`?

From what it seems, it looks like other integrations such as ruby and python allows filters, and other parameters to be passed.

Is it possible to make `browse` to accept these arguments?

**Comment by redox** [comment]
> Why does browse method for rails integration does not accept anything else other than page and hitsPerPage?

Hmmm, what `browse` method are you talking about? The one from the underlying Ruby API client?

**Comment by redox** [comment]
> From what it seems, it looks like other integrations such as ruby and python allows filters, and other parameters to be passed.

Yes, the recent versions of the Ruby API client also supports it: https://github.com/algolia/algoliasearch-client-ruby/blob/master/lib/algolia/index.rb#L168-L178

**Comment by brokenfingers** [comment]
It's the `browse` to browse all index. `Model.index.browse`

**Comment by redox** [comment]
> It's the browse to browse all index. Model.index.browse

Yes, so that has nothing to deal with the rails gem -> it's the underlying [Ruby API client](https://github.com/algolia/algoliasearch-client-ruby). That being said, it does provide all query parameters: https://github.com/algolia/algoliasearch-client-ruby#backup--export-an-index---browse like the other API clients. Are you using the latest version?

**Comment by brokenfingers** [comment]
I am using the rails gem and it does not allow the passing of a params to the method.

**Comment by redox** [comment]
> I am using the rails gem and it does not allow the passing of a params to the method.

It should; what is the version of the underlying Ruby API client (it's a dependency of the Rails gem)?

**Comment by brokenfingers** [comment]
It looks like it doesn't have a dependency on the Ruby API client. I looked at both my Gemfile and the gemspec in this repo and I couldn't find it.

**Comment by brokenfingers** [comment]
I think updating the gem helped, also I think the docs should specify that the first argument that it accepts is the hash. Thanks for the help.
