### ISSUE TITLE
your test build has been broken for two months

### ISSUE THREAD

**Issue by vincentwoo** [algolia/algoliasearch-rails#142]
https://travis-ci.org/algolia/algoliasearch-rails/builds

**Comment by redox** [comment]
Hi @vincentwoo,

yeah we've a hard time figuring out why Travis has such a bad network resulting in either timeouts or failure :/ Definitely something we need to improve.

**Comment by redox** [comment]
Finally fixed by 627c6bd3792a1fa4077751fac217d05258e7148e
