### ISSUE TITLE
`add_slave` should be deprecated in favor of `add_replica`

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-rails#154]
We should stop using the word `slave` and use `replica` instead. The change is already propagated in the API, we now need to update our public methods.

I think `add_slave` should be renamed to `add_replica`, and any mention of the method in the documentation should be updated.

We should keep `add_slave` as an alias for `add_replica` for now, but throw a deprecation warning when used. It will be removed in a future major version.

**Comment by redox** [comment]
Sure 👍 Let's go for a few aliases :)

**Comment by pixelastic** [comment]
cc @Jerskouille do you think that's something you could handle?
