### ISSUE TITLE
How do I sort results from the Rails backend API?

### ISSUE THREAD

**Issue by dylankarr** [algolia/algoliasearch-rails#192]
What do I need to add to sort results in this example?

```
@posts = Post.search(params[:q], sort: 'desc(name)')
```

It doesn't say anywhere in the documentation.

**Comment by redox** [comment]
Hi @dylankarr,

For performance reason, Algolia has a very specific way to sort results -> the sorts must actually be defined at indexing-time, statically using the index settings. Therefore, if you want to have several sort orders, you need to target different indices.

You can read more about it here: https://www.algolia.com/doc/guides/relevance/sorting

**Comment by dylankarr** [comment]
Ok, but what do I pass to the `#search` method to target another index? It doesn't say anywhere in those docs.

**Comment by redox** [comment]
From the rails mode, you can use the `replica:` option to target a specific replica. See https://github.com/algolia/algoliasearch-rails#primaryreplica

**Comment by dylankarr** [comment]
Thanks!
