### ISSUE TITLE
Search on acts_as_taggable_on

### ISSUE THREAD

**Issue by jamesfzhang** [algolia/algoliasearch-rails#195]
The [`acts_as_taggable_on`](https://github.com/mbleigh/acts-as-taggable-on) gem creates a `tags` table with the name and number of objects with that tag. How do I create a Algolia index for these tags so that I can search popular tags? As far as I can tell the gem doesn't expose its `ActiveRecord::Base` class. Thanks!

**Comment by jamesfzhang** [comment]
I figured it out.

```ruby
# Modify ActsAsTaggableOn so tags can be index by Algolia

module ActsAsTaggableOn
  class Tag < ::ActiveRecord::Base
    include AlgoliaSearch

    algoliasearch disable_index: !Rails.env.production? do
      attribute :id, :name, :taggings_count
      attributesToIndex ['name']
      customRanking ['desc(taggings_count)']
    end
  end
end

```

**Comment by stoplion** [comment]
I'm doing the same but getting a `undefined method find_or_create_all_with_like_by_name'`. @jamesfzhang did you run into the same?
