### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by casiodk** [algolia/algoliasearch-rails#218]
Is there a best practice for adding authorization to Angolia. 

Lets say i have 2 Organizations that have some records each. Some records are public and some are private and only accessible for users logged in to that organization?

/Nic

**Comment by casiodk** [comment]
anyone?

**Comment by redox** [comment]
Hey @casiodk,

sorry I didn't see this GH issue during the WE.

We're used to address such authorization use-case with tags & [Secured API keys](https://www.algolia.com/doc/guides/security/api-keys/#secured-api-keys).

In your case, you would have records with the tag `public` and records with the tag `organization_#{organization_id}`. And at query time, you would query the index with the following secured API key (imagine you're part of the organization=42):

```
public_key = Algolia.generate_secured_api_key('SearchOnlyAPIKeyKeptPrivate', {filters: '(organization_42,public)'})
```

Using this new `public_key` to query the Algolia API will automatically filter all your queries by records having the tag `public OR organization_42`.

Does that make sense?

**Comment by casiodk** [comment]
Yes, but i want to make sure, that people from organization a can not access organization b´s private index/search result. Is that possible?

**Comment by casiodk** [comment]
I think the secured api keys is exactly what i need
thanks a lot

**Comment by redox** [comment]
> Yes, but i want to make sure, that people from organization a can not access organization b´s private index/search result. Is that possible?

Oh yes, that's 100% sure!

> I think the secured api keys is exactly what i need
> thanks a lot

Awesome :) You're welcome!

**Comment by casiodk** [comment]
'SearchOnlyAPIKeyKeptPrivate' is this the `Search-Only API Key` from the algolia dashboard?

**Comment by redox** [comment]
> 'SearchOnlyAPIKeyKeptPrivate' is this the Search-Only API Key from the algolia dashboard?

Yes (and feel free to generate more of them from the dashboard) -> just make sure it doesn't appear in your frontend code; otherwise the "Secured API keys" are not secure anymore :)

**Comment by casiodk** [comment]
I´ve made an endpoint that generates a secure search token based on the users abilities/authorizations - valid for 12 hours - and that is used by the frontend to perform the search.

**Comment by casiodk** [comment]
Thanks for helping
