### ISSUE TITLE
How do I manage to index across multiple accounts?

### ISSUE THREAD

**Issue by demonmind** [algolia/algoliasearch-rails#220]
I have an application that has multiple accounts and i need to specify a dynamic index name based on the account a user is at the moment ( a user can have 1 or more accounts ).

How can I achieve this? I tried a rails helper but it did not work. Is there any other way?

**Comment by redox** [comment]
> I have an application that has multiple accounts and i need to specify a dynamic index name based on the account a user is at the moment ( a user can have 1 or more accounts ).
> 
> How can I achieve this? I tried a rails helper but it did not work. Is there any other way?

Unfortunately, this is not something supported by this gem. We were discussing about a v2 (to be implemented during the next few months) => maybe this could be something we could implement there.

In the meantime, I recommend targeting the same index for all your users and tag the records with their ID. At query time, you can use our **Secured API Keys** to restrict the search to a subset of your index. You can read https://github.com/algolia/algoliasearch-rails/issues/218 to get more insights.
