### ISSUE TITLE
Stateful gem?

### ISSUE THREAD

**Issue by krismartin** [algolia/algoliasearch-rails#221]
Do you guys have any plan to make this gem stateful so we can keep track of which records have/have not been indexed?

**Comment by redox** [comment]
> Do you guys have any plan to make this gem stateful so we can keep track of which records have/have not been indexed?

Hmmm, I don't think we want to go this way. But I'm also curious to understand what issue you're currently experiencing with the indexing flow; I'm sure we can improve things defining additional `_changed?` methods or so.

Let me know!
