### ISSUE TITLE
Update algoliasearch Gem dependency

### ISSUE THREAD

**Issue by srodman7689** [algolia/algoliasearch-rails#222]
Hey guys, is there anyway you would be able to update the algoliasearch gem dependency to the newest version? The reason I ask is because we use this gem in our application and we need access to the newest functionality from the algoliasearch gem. If there is anything I can help do to make this happen I will.

**Comment by srodman7689** [comment]
Sorry I didn't let you guys know before when I made the PR to add the functionality I am talking about.

**Comment by redox** [comment]
We can do it in the `algoliasearch-rails` gem; but that's also something you can do on your side by just adding the `algoliasearch` deps in your Gemfile:

```ruby
gem "algoliasearch-rails"
gem "algoliasearch", "~> 1.13.0"
```

Would that be enough for you? I would prefer not to bump the version of the `algoliasearch-rails` as soon as there is a release of one of the deps.

**Comment by srodman7689** [comment]
That's awesome! Thanks man!

**Comment by redox** [comment]
> That's awesome! Thanks man!

👍
