### ISSUE TITLE
Filter results for unauthorized users

### ISSUE THREAD

**Issue by MatthiasRMS** [algolia/algoliasearch-rails#227]
We'd like to have our search behave as the github autocomplete (https://github.algolia.com/): users can only see public objects and their own object.
It's not clear in the documentation what is the best way to perform this. 

How would you advise indexing and filtering to do this ? 
I can index all my objects, but how can I search among 'public' objects and belonging to the current user ?

**Comment by redox** [comment]
Hi @MatthiasRMS,

so sorry for the late answer; we definitely need help on maintaining the GH issues flow on this project :/

The best way to handle such a "Secure" search is to use Algolia's [Secured API Keys](https://www.algolia.com/doc/tutorials/security/api-keys/secured-api-keys/how-to-restrict-the-search-to-a-subset-of-records-belonging-to-a-specific-user/) -> they allow you to filter searches while encrypting those filters in an API key.

Let us know you need more infos!
