### ISSUE TITLE
Update searchableAttributes for existing data

### ISSUE THREAD

**Issue by augustosamame** [algolia/algoliasearch-rails#228]
I am not getting the expected behaviour when adding the `searchableAttributes` parameter.

Up until now, I only searched by attribute `search_name`. But now I want to also search by `search_object` attribute. So I just added the field name like this:

`searchableAttributes ['search_name', 'search_object']`

However, Algolia is ignoring matching data in `search_object` and continues to only use `search_name` for results.

Am I missing something? Or is it that the new attribute will be searchable only for NEW records that are uploaded to the index?

**Comment by redox** [comment]
Hi @augustosamame,

this is indeed weird. Could you double-check the settings have been propagated to the API going to the "algolia.com > Indices > YourIndexName > Ranking" and confirm the `searchableAttributes` is well set there?

If not, make sure the indexing is not disabled in your dev environment. The settings should be set at class-loading time; so make also sure the classes are reloaded to propagate the change.

If that doesn't work, let us know by re-opening this issue 👍
