### ISSUE TITLE
Auto indexing non-existend record when running sidekiq

### ISSUE THREAD

**Issue by jonhue** [algolia/algoliasearch-rails#229]
I've got a weird issue when using [Sidekiq][1] with [Algoliasearch][2] in my Rails application.

Whenever I start sidekiq (`bundle exec sidekiq`), it automatically performs all actions I configured with Algoliasearch:

```ruby
# A post model

include AlgoliaSearch
algoliasearch if: :published?, enqueue: :trigger_sidekiq_worker do
    attributes :title, :subtitle, :content, :cached_votes_score, :cached_votes_total

    # the `searchableAttributes` (formerly known as attributesToIndex) setting defines the attributes
    # you want to search in: here `title`, `subtitle` & `description`.
    # You need to list them by order of importance. `description` is tagged as
    # `unordered` to avoid taking the position of a match into account in that attribute.
    searchableAttributes ['title', 'subtitle', 'unordered(content)']

    # the `customRanking` setting defines the ranking criteria use to compare two matching
    # records in case their text-relevance is equal. It should reflect your record popularity.
    customRanking ['desc(cached_votes_score)', 'desc(cached_votes_total)']
end

private

def self.trigger_sidekiq_worker(record, remove)
    ::Algolia::Blog::PostsWorker.perform_async(record.id, remove)
end
```

_Logs:_

    $ bundle exec sidekiq
    
    
             m,
             `$b
        .ss,  $$:         .,d$
        `$$P,d$P'    .,md$P"'
         ,$$$$$bmmd$$$P^'
       .d$$$$$$$$$$P'
       $$^' `"^$$$'       ____  _     _      _    _
       $:     ,$$:       / ___|(_) __| | ___| | _(_) __ _
       `b     :$$        \___ \| |/ _` |/ _ \ |/ / |/ _` |
              $$:         ___) | | (_| |  __/   <| | (_| |
              $$         |____/|_|\__,_|\___|_|\_\_|\__, |
            .d$$                                       |_|
    
    Signal TTIN not supported
    Signal TSTP not supported
    Signal USR1 not supported
    Signal USR2 not supported
    2017-04-25T18:50:30.134Z 5596 TID-c0loo INFO: Running in ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
    2017-04-25T18:50:30.134Z 5596 TID-c0loo INFO: See LICENSE and the LGPL-3.0 for licensing details.
    2017-04-25T18:50:30.135Z 5596 TID-c0loo INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
    2017-04-25T18:50:30.136Z 5596 TID-c0loo INFO: Booting Sidekiq 5.0.0 with redis options {:url=>nil}
    2017-04-25T18:50:30.138Z 5596 TID-c0loo INFO: Starting processing, hit Ctrl-C to stop
    2017-04-25T18:50:30.207Z 5596 TID-1nla70 Algolia::Blog::PostsWorker JID-262b2f8613a197637d05caf3 INFO: start
    2017-04-25T18:50:30.539Z 5596 TID-1nla70 Algolia::Blog::PostsWorker JID-262b2f8613a197637d05caf3 INFO: fail: 0.333 sec
    2017-04-25T18:50:30.540Z 5596 TID-1nla70 WARN: {"context":"Job raised exception","job":{"class":"Algolia::Blog::PostsWorker","args":[1,false],"retry":true,"queue":"default","jid":"262b2f8613a197637d05caf3","created_at":1493146072.768356,"enqueued_at":1493146072.768356,"error_message":"Couldn't find Blog::Post with 'id'=1","error_class":"ActiveRecord::RecordNotFound","failed_at":1493146230.538659,"retry_count":0},"jobstr":"{\"class\":\"Algolia::Blog::PostsWorker\",\"args\":[1,false],\"retry\":true,\"queue\":\"default\",\"jid\":\"262b2f8613a197637d05caf3\",\"created_at\":1493146072.768356,\"enqueued_at\":1493146072.768356}"}
    2017-04-25T18:50:30.541Z 5596 TID-1nla70 WARN: ActiveRecord::RecordNotFound: Couldn't find Blog::Post with 'id'=1

I don't know if that behaviour is intended as algolia seems to just try to index a record with the id of 1. As far as I understand it, it should only index after a record got created, deleted or updated.<br><br>
After the worker failed it starts over, so I accumulate a lot of memory. In some occasions, I also get a `LoadError` even though all my classes and namespaces are named correctly.

I don't know if the issue is with Algolia or Sidekiq.

  [1]: https://github.com/mperham/sidekiq/wiki/Getting-Started
  [2]: https://github.com/algolia/algoliasearch-rails#with-sidekiq

**Comment by redox** [comment]
Hi @jonhue,

could you tell us which version of the `algoliasearch-rails` gem you're using? We had an issue a while ago because the callback was in an `after_save` callback instead of `after_commit` and therefore Sidekiq was so fast that it was running before the object has actually been saved in the database.

If you're using the latest version; we'll need to dig deeper because the issue doesn't see very obvious to me :/

**Comment by jonhue** [comment]
@redox thanks for your quick reply!

I am indeed using the latest version from rubygems (1.19.1).

I think the issue does not have it roots with Sidekiq being so fast, as Sitekiq actually tries to index records which never got created at all.

**Comment by redox** [comment]
> I think the issue does not have it roots with Sidekiq being so fast, as Sitekiq actually tries to index records which never got created at all.

I have a hard time figuring it out :/ Can you confirm the record that is not found should actually be found (just in case it's related to a validation failure or something we didn't spot)?

**Comment by jonhue** [comment]
@redox 

> I have a hard time figuring it out :/ Can you confirm the record that is not found should actually be found (just in case it's related to a validation failure or something we didn't spot)?

No, the record cannot be found, because it does not exist. The problem is that algolia initiates the search.

**Comment by jonhue** [comment]
@redox Here are some [(full) example logs] (https://gist.github.com/jonhue/8ab9cc9d91fd5525d52f256949da7591) from my application after running `bundle exec sidekiq` for a few seconds in a development envirinment with an empty database. Hope that helps :)

**Comment by Jerskouille** [comment]
Does this behavior also happen after you clear you Sidekiq queues as I recommended you to do in my StackOverflow answer? :)

**Comment by jonhue** [comment]
@Jerskouille Hmm.. it seems like the process continues after clearing the queue.

**Comment by Jerskouille** [comment]
So as I said in the StackOverflow answer, the gem should have been able to handle the non-existing object gracefully, but in seems like your queue and our gem started not understanding each other.
I'm not sure why it failed, a few reasons could explain this.
Since this peculiar occurrence is fixed, I'll close the issue, but I'd be happy to investigate more if you were to experience this issue again.

**Comment by jonhue** [comment]
@Jerskouille 

I think algolia initiates the indexing of the non-existent records. And it does so on **every** restart of the application - causing a memory leak.

I think this happens while queueing the Sidekiq worker in the **algoliasearch** declaration of the model.

**Comment by Jerskouille** [comment]
It indeed did so with that object which stuck the queue because of the error.
However, if I understood correctly, it should now not be the case anymore, right?

**Comment by jonhue** [comment]
@Jerskouille

It still is the case :-)

**Comment by Jerskouille** [comment]
I'm not sure I understood correctly.
Are you saying that even after clearing your queue, you're still having this error:

```txt
2017-04-25T18:50:30.540Z 5596 TID-1nla70 WARN: {"context":"Job raised exception","job":{"class":"Algolia::Blog::PostsWorker","args":[1,false],"retry":true,"queue":"default","jid":"262b2f8613a197637d05caf3","created_at":1493146072.768356,"enqueued_at":1493146072.768356,"error_message":"Couldn't find Blog::Post with 'id'=1","error_class":"ActiveRecord::RecordNotFound","failed_at":1493146230.538659,"retry_count":0},"jobstr":"{\"class\":\"Algolia::Blog::PostsWorker\",\"args\":[1,false],\"retry\":true,\"queue\":\"default\",\"jid\":\"262b2f8613a197637d05caf3\",\"created_at\":1493146072.768356,\"enqueued_at\":1493146072.768356}"}
```

From your message:

> @Jerskouille Hmm.. it seems like the process continues after clearing the queue.

I had understood that it had fixed your issue

**Comment by Jerskouille** [comment]
So you're having two different issues here:
1. An error with an object which doesn't exist (which is the issue I'm trying to fix)
2. A big memory usage, which should have nothing to do with this gem, even in case of error. A failed job is just a job that should happen again in the future and should not take more memory. For more information, see https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#memory-bloat .

**Comment by Jerskouille** [comment]
If you do still have an error, could you share your Algolia related code (with the associated `sidekiq` worker).

**Comment by jonhue** [comment]
@Jerskouille I added the missing details to the initial comment

**Comment by Jerskouille** [comment]
Could you try using the code [we describe here](https://github.com/algolia/algoliasearch-rails#things-to-consider) for your sidekiq worker?
```ruby
class MySidekiqWorker
  def perform(id, remove)
    if remove
      # the record has likely already been removed from your database so we cannot
      # use ActiveRecord#find to load it
      index = Algolia::Index.new("index_name")
      index.delete_object(id)
    else
      # the record should be present
      c = Contact.find(id)
      c.index!
    end
  end
end
```

I'm not sure why we describe both, is there a way to guarantee the fact that `Model.find` won't fail with Sidekiq @redox ?

**Comment by jonhue** [comment]
@Jerskouille This code just ... works 💯 👍

**Comment by Jerskouille** [comment]
Awesome!
