### ISSUE TITLE
using `algolia_without_auto_index` scope is not thread safe

### ISSUE THREAD

**Issue by mcivorsteiner** [algolia/algoliasearch-rails#234]
I am using the `algolia_without_auto_index ` scope in code that is run in sidekiq, and when many jobs are queued up, the scope is not always honored and objects saved in the scope are still being auto_indexed.  Dug into it a bit and think the fact that the scope is using class level instance variables is the issue.

This is what the class method looks like now:

```
def algolia_without_auto_index(&block)
  @algolia_without_auto_index_scope = true
  begin
    yield
  ensure
    @algolia_without_auto_index_scope = false
  end
end
```

https://github.com/algolia/algoliasearch-rails/blob/master/lib/algoliasearch-rails.rb#L458

Pretty sure ruby class level instance variables are not thread safe, so I think thats what is causing this.  Anybody else seen this issue?

**Comment by mcivorsteiner** [comment]
I fixed this issue using `Thread.current` instead of the class instance variable:

```
def algolia_without_auto_index(&block)
  self.algolia_without_auto_index_scope = true
  begin
    yield
  ensure
    self.algolia_without_auto_index_scope = false
  end
end

def algolia_without_auto_index_scope=(value)
  Thread.current["algolia_without_auto_index_scope_for_#{self.name}"] = value
end

def algolia_without_auto_index_scope
  Thread.current["algolia_without_auto_index_scope_for_#{self.name}"]
end
```

**Comment by redox** [comment]
> Pretty sure ruby class level instance variables are not thread safe, so I think thats what is causing this. Anybody else seen this issue?

Arg, that's very likely a good point.

> I fixed this issue using Thread.current instead of the class instance variable:

That's awesome, I'm gonna review it!

**Comment by redox** [comment]
Gonna release it soon.
