### ISSUE TITLE
Sorting by attribute

### ISSUE THREAD

**Issue by mustela** [algolia/algoliasearch-rails#237]
Hey there, 

I'm trying to sort by a specific attribute, but can't find any documentation around it, the only way I see you can set the sorting criteria is using `customRanking` but I need to do the `attribute` one. 
![screenshot 2017-06-02 09 18 26](https://cloud.githubusercontent.com/assets/325222/26715091/9346081a-4774-11e7-8f82-ad6a0897cd58.png)

Is it supported through the API?

**Comment by redox** [comment]
Hi @mustela,

yes this is supported by the API, but I confess the UI is a bit confusing (cc @kokliKo). Sorting by a specific attribute actually means that we use that attribute as the first attribute of the ranking formula, and therefore you can make it like that using the following setting:

```
algoliasearch ... do
  # ....
  ranking ['asc(start_datetime_i)', 'typo', 'geo', 'words', 'filters', 'proximity', 'attribute', 'exact', 'custom']
end
```

Let us know if you need more help!

**Comment by mustela** [comment]
Perfect, it's working, thanks!

**Comment by matteodepalo** [comment]
@redox it seems like for virtual replicas the provided solution doesn't work as I get the error message

```
Algolia::AlgoliaHttpError: The following settings are forbidden in virtual replicas: ranking
```

Is there a way to put an attribute in first place in the ranking list of virtual replicas using the gem?

**Comment by redox** [comment]
> Is there a way to put an attribute in first place in the ranking list of virtual replicas using the gem?

No there isn't. But it's not a gem issue, it's a limitation of the underlying API. Having an attribute in first place of the ranking formula requires a real (non-virtual) replica as it drastically changes the way the records are sorted/ranked: therefore Algolia requires a full-copy of the data.
