### ISSUE TITLE
Cannot reach any host: execution expired

### ISSUE THREAD

**Issue by illustrarium** [algolia/algoliasearch-rails#244]
Hi, I can't index my model :cry:

There is my model
```ruby
class Customer < ApplicationRecord
  include AlgoliaSearch
  has_many :orders
  algoliasearch auto_index: true, auto_remove: true, per_environment: true do
    attribute :name, :surname, :phone, :address
  end
end
```
When try start "Customer.reindex!" from rails console I get "Cannot reach any host: execution expired".

Search is working, and I see GET requests in dashboard. But index is not updating at all.

**Comment by redox** [comment]
Hmmmm, are you sure the gem is well configured? Do you have setup the `AlgoliaSearch.configuration = { application_id: 'YourApplicationID', api_key: 'YourAPIKey' }` initializer and reloaded your console/spring to make sure it's loaded?

**Comment by illustrarium** [comment]
Yes, gem is configured. When I try searching I have POST requests on dashboard. But when "reindex" I have nothing.

initiallzer

```
AlgoliaSearch.configuration = {
  application_id: ENV['ALGOLIASEARCH_APPLICATION_ID'],
  api_key: ENV['ALGOLIASEARCH_API_KEY'],

  # uncomment to use backend pagination
  # pagination_backend: :will_paginate
  # pagination_backend: :kaminari
}
```
application.yml (use figaro gem)
```
ALGOLIASEARCH_APPLICATION_ID: ***
ALGOLIASEARCH_API_KEY: ***
ALGOLIASEARCH_API_KEY_SEARCH: ***
```

**Comment by illustrarium** [comment]
I was reading this [topic](https://github.com/algolia/algoliasearch-rails/issues/123) but in my case it not useful

**Comment by illustrarium** [comment]
algoliasearch-rails-example doesn't reindex too, with the same error. But search work correctly

**Comment by illustrarium** [comment]
![selection_025](https://user-images.githubusercontent.com/6093376/27905478-c1df9238-6248-11e7-9096-cbf1b3153318.png)

**Comment by redox** [comment]
Could you try `ping <YourApplicationID>.algolia.net` ? Looks like something is going wrong with the DNS. You can also try `ping <YourApplicationID>-dsn.algolia.net` (this one is used at search time, and therefore should work).

**Comment by illustrarium** [comment]
here is the result

![selection_027](https://user-images.githubusercontent.com/6093376/27907280-b3b550ec-624f-11e7-9edd-3a3cc94c5bbc.png)

**Comment by redox** [comment]
So weird :/ Could you make sure the underlying `algoliasearch` ruby gem (not the rails wrapper) is using the latest version? It should be 1.13.0.

**Comment by illustrarium** [comment]
`gem list`
```
algoliasearch (1.13.0, 1.12.7)
```
But in Gemfile.lock I have 1.12.7
```
algoliasearch (1.12.7)
      httpclient (~> 2.8.3)
      json (>= 1.5.1)
    algoliasearch-rails (1.19.1)
      algoliasearch (~> 1.12.4)
      json (>= 1.5.1)
```

If I deleting 1.12.7, rails doesn't starts.
How can I change it on latest version?

**Comment by illustrarium** [comment]
`bundle update`
doesn't help

**Comment by illustrarium** [comment]
May be it help
![selection_029](https://user-images.githubusercontent.com/6093376/27911974-cbd13c04-6263-11e7-870b-05b9e1311df5.png)

**Comment by illustrarium** [comment]
No ideas?

**Comment by illustrarium** [comment]
OK, I changed dependency in gem, and put [my version](https://github.com/illustrarium/algoliasearch-rails) in Gemfile, but it didn't help.

No in my Gemfile.lock 1.13.0 version algoliasearch gem:
```
GIT
  remote: git://github.com/illustrarium/algoliasearch-rails.git
  revision: db5752e648f82794d37d9652383ef083117e8021
  specs:
    algoliasearch-rails (1.19.1)
      algoliasearch (~> 1.13.0)
      json (>= 1.5.1)
```

**Comment by illustrarium** [comment]
Everything is OK on production server.

**Comment by julienbourdeau** [comment]
Hi @illustrarium ,
I know this topic is pretty old but did you figure out what was wrong and why it was working in production?

I doubt this would require a fix in this gem so I'm going to close this issue for now. I'll reopen if this is needed.

**Comment by thomas-profitt** [comment]
> Could you try `ping <YourApplicationID>.algolia.net` ? Looks like something is going wrong with the DNS. You can also try `ping <YourApplicationID>-dsn.algolia.net` (this one is used at search time, and therefore should work).

Thank you. DNS was my problem. I had a problem with this symptom, on production but not in development. I learned it was a DNS problem when I could ping the Algolia host if I using its IP rather than that domain name.
