### ISSUE TITLE
Calling reindex on record subset replaces entire index

### ISSUE THREAD

**Issue by mrgarland** [algolia/algoliasearch-rails#247]
As described in the docs, calling reindex! on a subset of records, ie: `MyModel.where(...).reindex!` updates all of the records in that subset. Calling `MyModel.where(...).reindex` (no exclamation) on the other hand, replaces the entire index with just the records in the subset.

I understand that this is the expected behavior when `reindex` is called on an entire Model, but it seems like bizarre behavior when operating on a subset. Is this intentional? If so, it seems like a case which should be called out explicitly in the docs. It is a pretty drastic difference for 'Update these records' to change to 'Remove all records except these' with a single character, and for the difference not to be highlighted here.

Thanks!

**Comment by redox** [comment]
> I understand that this is the expected behavior when reindex is called on an entire Model, but it seems like bizarre behavior when operating on a subset. Is this intentional?

Right, it's a weird behavior but "expected".


> If so, it seems like a case which should be called out explicitly in the docs. It is a pretty drastic difference for 'Update these records' to change to 'Remove all records except these' with a single character, and for the difference not to be highlighted here.

Right, I'll add a note in the doc because I'm afraid it's hard to do better :/

**Comment by redox** [comment]
Just pushed that internally, should be deployed to this repository soon.

<img width="855" alt="screen shot 2017-07-28 at 18 01 30" src="https://user-images.githubusercontent.com/29529/28725791-d8b0ef3e-73be-11e7-813f-bfb8f3d1dece.png">
