### ISSUE TITLE
Copying Indices with Replicas

### ISSUE THREAD

**Issue by gtan66** [algolia/algoliasearch-rails#253]
Hi all,

What is the proper way to copy an index with replicas to another index? Both indices have the same replicas with the same settings. Getting the error  "cannot copy to a primary/replica index" when using `Algolia.copy_index!`. If this isn't possible, I'd like to know what the recommended workaround would be.

Thanks, 
Grace

**Comment by redox** [comment]
Hi @gtan66,

Good question! And I assume that's for "full reindexing" purposes? What you should do is build the new index without replicas and while moving it to the current one (that is attached to replicas) the new index will automatically inherit from them.

For such "non-rails related" question, don't hesitate to reach out to our [community forum](https://discourse.algolia.com/); easier to make sure you get an answer!

Let us know if that helps!

**Comment by gtan66** [comment]
@redox thank you! the community forum was indeed what i was looking for :)
