### ISSUE TITLE
Support for algolia_browse and not just algolia_search

### ISSUE THREAD

**Issue by ian** [algolia/algoliasearch-rails#274]
There doesn't seem to be support for the browse method, just search.  By default Algolia seems to apply pagination of 20/page.

A use case for this would be download CSV functionality.

**Comment by redox** [comment]
> There doesn't seem to be support for the browse method, just search. By default Algolia seems to apply pagination of 20/page.

> A use case for this would be download CSV functionality.

Right, for that I would encourage you to use the underlying Ruby API client. You can access it using the `index` class method, something like:

```ruby
MyModel.index.browse do |hit|
  # TODO
end
```

Let me know if that makes sense!
