### ISSUE TITLE
Clarify multiple indices configuration

### ISSUE THREAD

**Issue by oyeanuj** [algolia/algoliasearch-rails#277]
Hi @redox! Quick question - In the example provided for multiple indices, it seems that the other second index is defined inside the first index? 

Does that mean that the second index essentially inherits the configuration of the first index (like `attributes`, `searchableAttributes`) and that one needs to override them or redeclare them in each subsequent index that the model participates in?

Curious why each index-model relationship isn't a new method? (Or will that work as well?)

Thank you!

**Comment by redox** [comment]
> Hi @redox! Quick question - In the example provided for multiple indices, it seems that the other second index is defined inside the first index?
> 
> Does that mean that the second index essentially inherits the configuration of the first index (like attributes, searchableAttributes) and that one needs to override them or redeclare them in each subsequent index that the model participates in?

No they don't inherit from any of the setting; you need to re-specify all of them.

> Curious why each index-model relationship isn't a new method? (Or will that work as well?)

Yeah, I think that has been badly designed at the beginning. It's something we have in mind for the v2 of the gem.

**Comment by duhaime** [comment]
This issue is partially addressed by the open pull request https://github.com/algolia/algoliasearch-rails/pull/335
