### ISSUE TITLE
Algolia down does not affect website

### ISSUE THREAD

**Issue by 45sound** [algolia/algoliasearch-rails#28]
Hi,
While Algolia search was down(http://blog.algolia.com/black-thursday-dns-issue/) , my site was not able to start as in initializers, it was trying to connect via 

AlgoliaSearch.configuration = { application_id: ALGOLIA_APP_ID,
	                                api_key: ALGOLIA_API_KEY,
	                                pagination_backend: :kaminari }

I changed it to 

AlgoliaSearch.configuration = { application_id: ALGOLIA_APP_ID,
	                                api_key: ALGOLIA_API_KEY,
	                                hosts: ["#{ALGOLIA_APP_ID}-1.algolia.net", 
				                                	"#{ALGOLIA_APP_ID}-2.algolia.net", 
				                                	"#{ALGOLIA_APP_ID}-3.algolia.net"],
	                                pagination_backend: :kaminari }

and this works. But sometime in the future, this may fail for unknown reasons. Would having a begin/rescue help, or is there a way to mock out algoliasearch(in the models) if there is not a valid connection. My current models use:

algoliasearch per_environment: true, :disable_indexing => Proc.new { Rails.env.test? || Rails.env.development? } do
    ...
end

**Comment by redox** [comment]
I think this can now be achieved with https://github.com/algolia/algoliasearch-rails#exceptions
