### ISSUE TITLE
Documentation Clarification of reindex

### ISSUE THREAD

**Issue by bemky** [algolia/algoliasearch-rails#284]
I recently dumped 1M + records from our index on accident because I read: 
<img width="928" alt="screen shot 2017-12-12 at 11 15 16 am" src="https://user-images.githubusercontent.com/841033/33898602-94cbd618-df2e-11e7-8b27-4afef7ea6057.png">

I did not read down to the section entitled "Reindexing".

I am not the engineer that set this up, but I was adding a new model to our global index (that searches several models), and I read the above lines and figured `Toy.reindex` would reindex all Toy models... which is a fair conclusion after reading above. Of course, after emptying our entire index, and reading further in the docs, I now understand what happened.

You might want to add that `Toy.reindex` reindexes all of \***Toy's index\***, which in my case was our global index of lots of models, and reindexing means **\*dumping all\*** and adding existing models.

**Comment by julienbourdeau** [comment]
Sorry for the unintended operations.

I opened PR to our doc to add a note about multiple indices. Our readme is generated from the documentation, when the doc team merges it, the readme will be updated.
