### ISSUE TITLE
Attribute aliases

### ISSUE THREAD

**Issue by pjforde1978** [algolia/algoliasearch-rails#309]
I've got a Rails model with an attribute named release_date which I store in my Algolia index as 'year' for cosmetic reasons.

Instead of:
```
attribute :year do
  release_date
end
```
it might be nice to support syntax like:

`attribute :year => :release_date`

For one or two attributes, block syntax isn't such a big deal. It's a bit more laborious when you have several attributes.

**Comment by julienbourdeau** [comment]
Hi @pjforde1978 Thanks for the feedback.
I'll look into and see how we could simply it. I agree that once you have a lot of small blocks, it could start to be painful.

**Comment by julienbourdeau** [comment]
Hi @pjforde1978,

What do you think of something that let you define one method to serialize the whole entity. I have something like this in mind:

Instead of writing
```ruby
class Article < ApplicationRecord
  include AlgoliaSearch

  algoliasearch do
    attribute :title, :text, :created_at, :extra_attr
  end

  def extra_attr
    'This is Rails 🚀'
  end
end
```

You would have something like
```ruby
class Article < ApplicationRecord
  include AlgoliaSearch

  algoliasearch do
    serialize_with :searchable_attr
  end

  def searchable_attr
    {
        :title => self.title,
        :text => self.text.sub(#do something here),
        :created_at => self.created_at.strftime("%Y-%m-%d"),
        :extra_attr => 'This is Rails 🚀'
    }
  end
end
```

**Comment by pjforde1978** [comment]
I mean, in that example you could even just pass a hash to serialize_with, as the send to searchable_attr is just returning a hash anyhow, right?

But yes, this would be lovely. It's been my experience with custom serializers that they are the rule, not the exception.

**Comment by julienbourdeau** [comment]
I will work on supporting ActiveModel::serializer support. Sylvain already started here #266, I'll make sure it's merged quickly.
Ideally, I'd rather not add the Alias feature as it would add another thing.

**Comment by Spone** [comment]
#266 has been merged and released in 1.21.0 :)

**Comment by julienbourdeau** [comment]
It seems like the serializer is a good option and modifying the `attribute` method is not so trivial.
I tried to add "options" yesterday, related to issue #321. So I think I'll close this one.

Also, about the original issue, I think you can do
```ruby
attribute :year { release_date }
```
which is pretty close to `attribute :year => .release_date`. What do you think @pjforde1978 ?

**Comment by pjforde1978** [comment]
It's just the alternative form of do...end but you're right - no reason not to use it. :shipit:

**Comment by Spone** [comment]
Actually this syntax is not valid Ruby:

    attribute :year { release_date }

It throws a `SyntaxError`:

```
SyntaxError: /builds/project/app/models/program.rb:55: syntax error, unexpected '{', expecting keyword_end
      attribute :year { release_date }
                              ^
/builds/ferdi/ferdi.fr/app/models/program.rb:55: syntax error, unexpected '}', expecting keyword_end
...year { release_date }
...                                ^
```

**Comment by julienbourdeau** [comment]
Hi @Spone,

I think if you want to use the shorthand for block, the parenthesis around the method arguments become mandatory. It's not as nice looking but i think it's fine. My guess is taht ruby doesn't allow it to avoid confusion beween a hash as a second argument and a block but I don't know.

I just ran the following snippet and it works.
```ruby
attribute (:year) { release_date }
```
