### ISSUE TITLE
Associated Records

### ISSUE THREAD

**Issue by superacidjax** [algolia/algoliasearch-rails#31]
Given the following model:

``` ruby
class Profile < ActiveRecord::Base
  include AlgoliaSearch

  belongs_to :user, touch: true, dependent: :destroy
  has_many :licenses
  has_many :specializations
  has_many :specialties, through: :specializations

  algoliasearch do
    add_attribute :profile_user
    add_attribute :profile_licenses
    add_attribute :profile_specialties
  end

  def profile_user
    self.user
  end

  def profile_licenses
    self.licenses
  end

  def profile_specialties
    self.specialties
  end
end
```

The index is happening, and in the Algolia Dashboard it shows the associated items (for example "profile_licenses") However, two things:
1. How do I limit the fields indexed for associated models?
2. What would could the associated models to return undefined in the front-end JS search. Meaning -- the associated data is showing in the Algolia dashboard, but on search, anything that was an associated record is returning undefined.

**Comment by iffyuva** [comment]
@redox in the above example, does changing user attributes like name or email automatically reindex profile record?

**Comment by redox** [comment]
@iffyuva no it will not, you need to trigger the indexing of the associated profile yourself. It will be automatic once we fix https://github.com/algolia/algoliasearch-rails/issues/40.

**Comment by iffyuva** [comment]
@redox thanks for the update.
