### ISSUE TITLE
Clarify recommendation on _changed? for custom attributes in Rails 5.2

### ISSUE THREAD

**Issue by oyeanuj** [algolia/algoliasearch-rails#316]
Hi @raphi @redox , quick question/clarification: 

In [this section on custom attributes](https://github.com/algolia/algoliasearch-rails#custom-attribute-definition), the example suggests creating `{attribute}_changed?` which further checks if a model attribute has changed.

In Rails 5, when used within after_* callbacks, they throw a deprecation notice. So, maybe the doc should clarify if Algolia calls the `_changed?` methods in the `after_*` callbacks, and if so, update the examples to reflect the newer code syntax?

**Comment by mmhan** [comment]
Bump

**Comment by julienbourdeau** [comment]
I have refreshed the docs for our Rails gem. Please find the temporary docs here: https://deploy-preview-2711--algolia-doc.netlify.com/doc/framework-integration/rails/indexing/indexing/?language=php#indexing-only-if-attributes-have-changed

I'm hoping this is clearer. If you need more details, please let me know and I will reopen this issue 👍
