### ISSUE TITLE
How to support optional nested attribute?

### ISSUE THREAD

**Issue by wayne5540** [algolia/algoliasearch-rails#321]
Example:

```rb
class Profile < ActiveRecord::Base
  include AlgoliaSearch

  belongs_to :user, optional: true

  algoliasearch do
    attribute :user do
      { name: user.name, email: user.email }
    end
  end
end
```

In this case, if we have profile without user relation, `Profile.reindex!` will just raise `Undefined method for nil` error, I know there are many solutions to fix it, there are 2 fixes come to my mind

1. Adding a `try()` method

```rb
class Profile < ActiveRecord::Base
  include AlgoliaSearch

  belongs_to :user, optional: true

  algoliasearch do
    attribute :user do
      {
        name: user.try(:name),
        email: user.try(:email)
      }
    end
  end
end
```

2. Adding a if else condition

```rb
class Profile < ActiveRecord::Base
  include AlgoliaSearch

  belongs_to :user, optional: true

  algoliasearch do
    attribute :user do
      user.blank? ? {} : {
        name: user.name,
        email: user.email
      }
    end
  end
end
```

However, I don't like either way, it feels little tricky to me, is there a better way to fix? If so, we should consider add it to README. If no, is there anything we could do? for example adding a `optional: true` option to `attribute` method?

Thanks

**Comment by julienbourdeau** [comment]
Hi @wayne5540,

I would recommend using a custom attribute. What do you think of the following?

```ruby
class Profile < ActiveRecord::Base
  include AlgoliaSearch

  belongs_to :user, optional: true

  algoliasearch do
    attribute :user
  end

  def user
    user.blank? ? {} : {
        name: user.name,
        email: user.email
    }
  end
end
```

**Comment by wayne5540** [comment]
Hi @julienbourdeau,

Thanks for your suggestion, custom attribute is a good way to make code more readable :wink:. However, it still has some downsides, for example:

1. We can't name it `user` because we already had a `user` association, so it has to be other name like `algolia_user` maybe?
2. Since we can't name it as `user` which is the most intuitive name, other name will be less intuitive compare to `user`
3. Still handy (if else condition)

In my humble opinion, it will be good if we have API like below:

```rb
class Profile < ActiveRecord::Base
  include AlgoliaSearch

  belongs_to :user, optional: true

  algoliasearch do
    # When user is nil, return {}
    attribute :user, optional: true do
      {
        name: user.name,
        email: user.email
      }
    end
  end
end
```

Or even

```rb
class Profile < ActiveRecord::Base
  include AlgoliaSearch

  belongs_to :user, optional: true

  algoliasearch do
    # When user is nil, return default value
    attribute :user, default: {} do
      {
        name: user.name,
        email: user.email
      }
    end
  end
end
```

I prefer the later one, how do you think?

**Comment by julienbourdeau** [comment]
I also prefer the second solution, I like the `:default` option!

To be honest, I'd rather not add way to do things. There are already quite a few different way to serialize the models. We might add the feature one day, typically in a v2. But I'd rather keep things simple for now, and focus or more important bugs and improvements.

You can also extract all this logic into a ModelSerializer. Temporary docs is available here: 
https://deploy-preview-2711--algolia-doc.netlify.com/doc/framework-integration/rails/indexing/serializing-models/?language=php#using-activemodel-serializer 
(it will be published soon)

Thanks a lot for you suggestions and feedback 🙏 I hope you understand my reasoning here. 👍 

Examples from the doc:

```ruby
class Contact < ActiveRecord::Base
  include AlgoliaSearch

  algoliasearch do

    # Sending 3 model attributes
    attributes :first_name, :last_name, :email

    # Sending a dynamic attribute defined by instance method
    attribute :full_name

    # Aliasing birth_date attribute to dob with shorthand block syntax
    attribute (:dob) { birth_date }

    # Nesting the company information for organization-sake
    attribute :company do
      { name: company_name, website: company_website }
    end

  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

```
