### ISSUE TITLE
Test Suite is a little Flaky

### ISSUE THREAD

**Issue by simonireilly** [algolia/algoliasearch-rails#323]
### Context
Running the test suite with `bundle exec rspec`
1. When I point to a blank Algolia App the tests pass.
1. When I run them again they fail.

### Impact
#319 shows this error is affecting PR's

### Fix
I fixed this locally and on CI by deleting all the indexes after the suite has run. Then the next run starts on a clean Algolia App.

```ruby
#spec_helper.rb
  c.after(:suite) do
    # Sort these so we don't try and delete a replica
    indices = Algolia.client.list_indexes()['items'].sort_by { |index| index["primary"] || "" }
    indices.each do |index|
      # Bang on the delete so we wait for the task to finish
      Algolia.client.delete_index!(index['name'])
    end
  end
```

I would open up a PR - **but since this deletes all indices between runs i didn't want to put side effects onto your testing application** - particularly if you are sharing this app between instances.

I test this multiple times in CI and locally and it passes without a hiccup.
Open PR in my Fork [Fix test suite failure](https://github.com/simonireilly/algoliasearch-rails/pull/2) 

@julienbourdeau 
@redox

Appreciate your time.

**Comment by julienbourdeau** [comment]
Hi @simonireilly,

Thank you for looking into it! I think many people (at least me) have different projects using the same app, so I'd rather not delete all indices. What we could do is define some norm in the [safe_index_name](https://github.com/algolia/algoliasearch-rails/blob/master/spec/spec_helper.rb#L32-L36) and only delete indexes matching this pattern.

The approach we had in other projects is either to:
* Delete the index before using it
* Save the name of all index created, delete them at the end

First one works every time, the second one might not work if your tests suite breaks. 💥 
For example, in PHP, if you get a fatal error, your clean up code never get executed.

What do you think?

**Comment by simonireilly** [comment]
Hi @julienbourdeau,

I agree deleting all indexes is too dangerous.

#### Option 1 - Delete the index before using it

This means all contributors have to follow the pattern which can give some human error. To fix this you would maybe write a `rspec` hook like:

```ruby
before(:each) do 
  AlgoliaSearch.included_in.each do |klass| 
    Algolia.client.delete_index!(klass.index.name)
  end
end
```
This gets messy. You need to delete the Primary, then replicas/slaves. There is also a high overhead and I found I got some edge cases that left a lot of `if`'s hanging around.

#### Option 2 - Save the name of all index created, delete them at the end

In my opinion this is easier. I have the following suggestion for this. I prefer to use the algolia client to get the list of indexes because I need to sort. I need to ensure that I don't attempt to delete a replica or slave before I delete the primary.

1. Remove reliance on ENV['TRAVIS_JOB_NUMBER'] so local and CI behaviour is the same
1. Store a SecureRandom constant to prefix all index names so we get `ea5f1cd615b24f6b_Book_development`
1. Rspec `after(:suite)` will run on early exit - will only fail if test suite configuration doesn't evaluate.
1. We are now using `SecureRandom` - this solves the underlying issue anyway - because now all index names are always unique. The delete step is no longer required to make subsequent runs work. It is now just a cleanup opperation.

```ruby
RSpec.configure do |c|
  ...
  # Remove all indexes setup in this run in local or CI
  c.after(:suite) do
    safe_index_list.each do |index|
      Algolia.client.delete_index!(index['name'])
    end
  end
end

# A unique prefix for your test run in local or CI
SAFE_INDEX_PREFIX = SecureRandom.hex(8).freeze

# avoid concurrent access to the same index in local or CI
def safe_index_name(name)
  "#{SAFE_INDEX_PREFIX}_#{name}"
end

# get a list of safe indexes in local or CI
def safe_index_list
  Algolia.client.list_indexes()['items']
    .select { |index| index["name"].include?(SAFE_INDEX_PREFIX) }
    .sort_by { |index| index["primary"] || "" }
end
```

I have tested both these options on my fork, but prefer option 2 - https://github.com/simonireilly/algoliasearch-rails/pull/2

It might also be good to specify that indexes are not deleted if you pass a flag e.g. `bundle exec rspec --debug`. SecureRandom will ensure the next test run is successful even without the delete, and you can inspect your previous indexes to do any debugging.

What do you think?

**Comment by julienbourdeau** [comment]
Oh I really like the second option! I don't think we tried this approach before. Do you mind opening a PR on this repo? I'd be happy to merge this solution.

There is another constraint I have in mind. For Travis, [we generate keys](https://blog.algolia.com/travis-encrypted-variables-external-contributions/) for each build but they have an index prefix constraint. I can edit the constraint but I need something fixed.
I'd like to have `rails_` so I guess we would have:

```ruby
SAFE_INDEX_PREFIX = "rails_" + SecureRandom.hex(8).freeze
```

Then, depending on how many indexes are created by the tests, we can create a batch to have one http call. It's generally better to send all operations and then wait, than wait between each operations. This might be early optimization, I don't know if the suite creates 3-5 indexes or 30 ^^
