### ISSUE TITLE
Regression: Library cannot be used without ActiveRecord loaded

### ISSUE THREAD

**Issue by rgalanakis** [algolia/algoliasearch-rails#328]
Due to https://github.com/algolia/algoliasearch-rails/pull/325/files#diff-dfaec67e907148ea8211e17340f0f30cR896

If ActiveRecord is not loaded (like, if you use Sequel without Rails), this line errors with: `uninitialized constant AlgoliaSearch::ClassMethods::ActiveRecord`

Bug is self-evident so I didn't fill in the rest of the template.

**Comment by julienbourdeau** [comment]
> If ActiveRecord is not loaded (like, if you use Sequel without Rails)
Out of curiosity, could you tell me more about this use case?

This is definitely a regression, I'll fix it and release a new patch version! Thank you for opening this issue 👍

**Comment by rgalanakis** [comment]
Hi Julien, thanks for the quick response.

Our API uses Grape and Sequel. For a certain type of search/request, we proxy an Algolia search through the backend so we can do some additional validation/filtering/enrichment/shape coercion.

This project was a great help over using the underlying AlgoliaSearch gem directly, very similar to what I was about to write myself but way way better obviously. I think when I set it up there was a small issue with Sequel-no-Rails, but otherwise it's worked fine.

**Comment by julienbourdeau** [comment]
Ok that's really good to hear 👌 

Would you mind testing this PR: https://github.com/algolia/algoliasearch-rails/pull/329 it doesn't seem easy to reproduce ^^

**Comment by rgalanakis** [comment]
Worked great, thanks!
