### ISSUE TITLE
Slave index are not binded to master

### ISSUE THREAD

**Issue by andreacfm** [algolia/algoliasearch-rails#35]
When I set a slave index this is not automatically binded to master.

```ruby
    add_slave 'User_name_asc', per_environment: true do
      customRanking %w(asc(name))
    end
```

An index User_name_asc_[env] is created but id not a slave of the master index created by the class

**Comment by andreacfm** [comment]
My fault sorry

**Comment by redox** [comment]
Alright :) Let us know if something wasn't clear enough in the documentation.
