### ISSUE TITLE
1.22 breaking change

### ISSUE THREAD

**Issue by Gasparila** [algolia/algoliasearch-rails#352]
- Rails version: 5.1.6
- Algolia Rails integration version:  1.22

### Description
https://github.com/algolia/algoliasearch-rails/pull/338 introduced a few
breaking changes (including 1 fixed in https://github.com/algolia/algoliasearch-rails/pull/350).

https://github.com/algolia/algoliasearch-rails/pull/338/files#diff-dfaec67e907148ea8211e17340f0f30cR749 changed the behavior
for when `<attribute>_changed?` doesn't exist. Previously it would
be conservative and always auto-index if there are custom attributes. 
Now it will assume no changes are necessary 

### Steps To Reproduce
```rb
class AnyModel < ActiveRecord::Base
  include AlgoliaSearch
  algoliasearch do
    attribute(:not_a_column) { some_column + 1 }
  end
end

instance_of_model.update!(some_column: 3) # will not trigger algolia update
```

**Comment by Spone** [comment]
We've experienced the same bug and it was hard to debug... Please Algolia be careful with regressions 🙏

**Comment by Gasparila** [comment]
Reopening because this was fixed in our fork (which you are welcome to use @Spone) but has not yet been merged into this repo. PR here: https://github.com/algolia/algoliasearch-rails/pull/354
