### ISSUE TITLE
`rake algoliasearch:reindex` doesn't do anything. 

### ISSUE THREAD

**Issue by joshuapinter** [algolia/algoliasearch-rails#37]
Hi Guys, 

I'm trying to index all of my `AlgoliaSearch` models for the first time. Was going to write a quick `rake` task to do this for me but I found you guys already had done that. The only thing is, I run it and it doesn't do anything. :/

I investigated a little further and it seems like the `AlgoliaSearch::Utilities.get_model_classes` returns an empty `Array`. 

Is there anything I should know about here?

Thanks. 

Josh

**Comment by redox** [comment]
Hmmm you're right; that's an old rake task I wrote. I generally run "MyModel.reindex" for a complete reindexing, I'll investigate why `AlgoliaSearch::Utilities.get_model_classes` isn't returning anything.

**Comment by joshuapinter** [comment]
Sounds good. It's a handy rake task to have. I was literally going to write something similar, except it would loop through all the models in the `app/models` directory and call a `reindex` on any model that responds to it. Yours seems to have a lot more smarts to it, if you can get it working again. 

Also would be a great addition to the **Quick Start** guide of the README.

Let me know if I can help.

**Comment by edenvicary** [comment]
Any progress on this, because its not working for me either.

**Comment by joshuapinter** [comment]
@edenvicary I made a little rake task that we used instead: 

```ruby
namespace :algolia_search do

  desc "Reindexes all of the models that include AlgoliaSearch module."
  task :reindex => :environment do |t, args|

    Rails.application.eager_load! # Ensure all models are loaded (not necessary in production when cache_classes is true).

    algolia_models = ActiveRecord::Base.descendants.select{ |model| model.respond_to?(:reindex) }

    puts "Reindexing #{algolia_models.count} models."

    algolia_models.each do |algolia_model|
      say "Reindexing #{algolia_model} model:"

      say "#{algolia_model.count} records.", true

      algolia_model.reindex
    end
      
  end

end
```

**Comment by edenvicary** [comment]
Thanks @joshuapinter, did you consider making a pull to get it fixed in this repo?

**Comment by joshuapinter** [comment]
@edenvicary Yeah, good call. I'll put this on the ToDo list for the week.

**Comment by redox** [comment]
Thank you for contributing guys, I would just replace `respond_to?(:reindex)` with `respond_to?(:algolia_reindex)` to ensure we're not considering wrong model.

**Comment by joshuapinter** [comment]
Will do @redox!

In the PR, would you like me to update the [`AlgoliaSearch::Utilities.get_model_classes`](https://github.com/algolia/algoliasearch-rails/blob/master/lib/algoliasearch/utilities.rb#L4) as well or do you just want the rake task to be updated?

**Comment by redox** [comment]
@joshuapinter yeah I think we should update that method as well, never investigated why it's not working :/

**Comment by joshuapinter** [comment]
@redox Okay, I'll take a proper look this week and submit a PR.

@edenvicary For now I'd say just use a custom rake task.

**Comment by edenvicary** [comment]
Awesome @redox and @joshuapinter you guys are legionds.

**Comment by joshuapinter** [comment]
Ha. No, @redox is the legend.

**Comment by albandum** [comment]
Hello guys, any news on this PR ? For now I'll just take @joshuapinter rake task, but it would be great to have a reindex task :) I naively didn't even look if it worked well and ended up having some trouble in prod with non-indexed models

**Comment by redox** [comment]
> Hello guys, any news on this PR ? For now I'll just take @joshuapinter rake task, but it would be great to have a reindex task :) I naively didn't even look if it worked well and ended up having some trouble in prod with non-indexed models

Right, sorry about not fixing that. Our users are mostly reindexing their model one by one doing `MyModel.reindex` so it was never a very prioritary bug.

I think we just need to replace `respond_to?(:reindex)` by `respond_to?(:algolia_reindex)` and call that `algolia_reindex` method and we're good to go. What do you think @albandum ?

**Comment by joshuapinter** [comment]
@redox I never ended up digging in to this, sorry. But I'll chime in here. 

One of the main reasons why the built-in rake task doesn't do anything is because `AlgoliaSearch::Utilities.get_model_classes` comes up as `[]` for me, even though I have two models being indexed.

In my rake task, I determine which models are being indexed by seeing which ones respond to `reindex`, with this: 

```ruby
algolia_models = ActiveRecord::Base.descendants.select{ |model| model.respond_to?(:reindex) }
```

Digging a little further, `AlgoliaSearch.included_in` is always nil for me, which is found in the `get_model_classes` method.

You'll need to update how you get the list of models that are being indexed in order to fix the `reindex` rake task.

Let me know if you need a hand.

**Comment by redox** [comment]
@joshuapinter happy to go your way, not sure why the `included_in` is not working... This logic has been initially copied from `sunspot` (the Solr+rails gem) but very happy to change.

Would love to merge your alternative solution if you want to submit a PR @joshuapinter 👍

**Comment by joshuapinter** [comment]
Sounds good. I'll get to that later today. But I actually will this time. :)

**Comment by joshuapinter** [comment]
Issued a PR to update the built-in reindex rake task.

Not only does it work now but it has a much cleaner and informative output. Here's a sample of what it looks like when you run it: 

![screenshot 2017-03-01 11 07 01](https://cloud.githubusercontent.com/assets/180819/23473952/567bcf62-fe6f-11e6-9f75-57ed10e51381.png)

**Comment by joshuapinter** [comment]
👍
