### ISSUE TITLE
Support array as parameter for _geoloc

### ISSUE THREAD

**Issue by chloelbn** [algolia/algoliasearch-rails#370]
The current Rails implementation does not support passing an array as a parameter for `_geoloc` ([see doc](https://www.algolia.com/doc/framework-integration/rails/indexing/serializing-models/?language=ruby#coordinates-geolocalisation)). However, this feature [is supported by the Algolia search engine](https://www.algolia.com/doc/guides/managing-results/refine-results/geolocation/#enabling-geo-search-by-adding-geo-info-to-records), so it needs to be fixed.

**Comment by ldlgds2** [comment]
A temporary workaround is:
```
def _geoloc
  [{ lat: x_1, lng: y_1 }, { lat: x_2, lng: y_2 }, { lat: x_3, lng: y_3 }]
end

algoliasearch do
  attributes :_geoloc
end
```

**Comment by ldlgds2** [comment]
What about this patch?

```
    def geoloc(*args)
      raise ArgumentError.new('Cannot specify additional attributes on a replica index') if @options[:slave] || @options[:replica]
      add_attribute :_geoloc do |o|
        args.is_a?(Array) ? args : [args]
      end
    end
```

**Comment by ldlgds2** [comment]
@chloelbn : I found a fix. I am patching the gem code and am looking forward to your kind reviewing.
