### ISSUE TITLE
Incompatibility with the new 'algolia' gem

### ISSUE THREAD

**Issue by GuillaumeWrobel** [algolia/algoliasearch-rails#388]
### Description

As `algoliasearch-rails` requires:
- algoliasearch (>= 1.26.0, < 2.0.0)
- json (>= 1.5.1)

if you include the new [Algolia search gem](https://github.com/algolia/algoliasearch-client-ruby/blob/master/upgrade_guide.md), you end with a conflict between two `analytics.rb` files:

```
algolia-2.0.0/lib/algolia/config/analytics_config.rb:2:in `<module:Algolia>': Analytics is not a module (TypeError)
algoliasearch-1.27.5/lib/algolia/analytics.rb:3: previous definition of Analytics was here
```

### Steps To Reproduce

add to your gemfile:

```ruby
gem 'algoliasearch-rails'
gem 'algolia'
```

launch `rails console`

**Comment by chloelbn** [comment]
Hi @GuillaumeWrobel ! Indeed we're aware of that, and a new major version of the `algoliasearch-rails` gem including the v2 of the `algolia` gem will be out in the next 3 months! We thank you for your patience in the meantime

**Comment by GuillaumeWrobel** [comment]
Ok, maybe you could write a warning phrase about this incompatibilty in both gems readme :bulb:

**Comment by Spone** [comment]
Hi @chloelbn it's been 3 months since your message. Do you have news about this new `algoliasearch-rails` major version? :)

**Comment by marckohlbrugge** [comment]
Just wanted to add my vote to this. In the hope those in charge can devote some additional resources to the development of this gem.

**Comment by acallaghan** [comment]
Why was this issue closed - this Rails gem is still incompatable with the ruby one?

**Comment by benbonnet** [comment]
@marckohlbrugge let's just deal with the fact that those in charge might want us to understand that they don't give a damn f**k about the issue

that is, can say it still happens and that for now we're quite stuck with the situation

**Comment by chloelbn** [comment]
Hi @benbonnet ! Do you mean you're using both `algoliasearch` gem and `algolia` ?

**Comment by benbonnet** [comment]
Hello;

```
gem 'algoliasearch-rails'
gem 'algoliasearch'
```

We'd like to migrate to `algoliasearch-rails`, plan to drop `algoliasearch`. But we're stuck with the same error (`analytics_config.rb:2:in <` etc...)

**Comment by duhaime** [comment]
Hi @chloelbn is there a commit or release that closed this? If so, can you please link to it?

**Comment by duhaime** [comment]
@chloelbn I think this issue should be reopened as several teams are encountering this issue...

**Comment by DevinCodes** [comment]
Hi @duhaime !

version `2.x` of this gem adds support for the `algolia` gem. If you can upgrade to that version, you should no longer have to rely on the `algoliasearch` gem. If your project relies on that _on top_ of the `algoliasearch-rails` gem, I'd recommend staying on version `1.x`, or upgrading the `algoliasearch` gem to the `algolia` one. Hope that helps! 🙂
