### ISSUE TITLE
Reindex the record on after_touch

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-rails#40]

**Comment by wellinformed** [comment]
I have an after_touch handler in my model to handle this:

```after_touch :index!```

Fairly ambivalent out whether or not it should happen automatically.

**Comment by chrisyeung1121** [comment]
any example on how the `index!` method look like if I have a `has_many` association?

**Comment by redox** [comment]
Something like that I think:

```ruby
class User
  has_many :profiles
  after_touch :index!

  algoliasearch do
    # ....
  end
end

class Profile
  belongs_to :user, touch: true
end
```

**Comment by matisoffn** [comment]
I have it working in my project, this is the code being used:

```ruby

class AssociationThroughModel
  after_touch :reindex_parent

  private

  def reindex_parent
    ParentModel.index_objects [self.parent_model]
  end
end
```

**Comment by redox** [comment]
Let's keep only #74.
