### ISSUE TITLE
index_name/settings  end point still being called while disable_indexing: true

### ISSUE THREAD

**Issue by mmhan** [algolia/algoliasearch-rails#412]
- Rails version: 6.1.4.1
- Algolia Rails integration version: 2.1.3
- Algolia client version: 2.1.1
- Language Version: 2.6.7

### Description

It is my expectation that with `disable_indexing: Rails.env.test?`, there will be no http calls needed anymore for tests to pass without any internet connection. 

However it seems to be still calling the `:index_name/settings` end point and my tests are failing because of it.

The workaround would be to use `vcr` to cache/mock the responses, but what if I didn't want new dependencies like that?

### Steps To Reproduce

- Index an ActiveRecord model, DummyRecord with `disable_indexing: Rails.env.test?` 
- `DummyRecord.create` in test environment with internet disabled in a test type that is not model/view/controller. In my case, I am creating a record in a component test for ViewComponent.

**Comment by mmhan** [comment]
I have managed to find additional information that disable_indexing is working as intended for the main index, `/settings` endpoint are only getting called for the replicas even when `inherit: true` is option is given at `add_replica` method call.

**Comment by DevinCodes** [comment]
Thank you for reporting @mmhan! I'll try to take some time next week to see if there's a way to fix this. If you find a way before that time, though, feel free to open a PR 😄  Cheers!
