### ISSUE TITLE
No such file or directory @ rb_sysopen - debug.log (Errno::ENOENT)

### ISSUE THREAD

**Issue by jasich** [algolia/algoliasearch-rails#417]
- Rails version: 6.1.1
- Algolia Rails integration version: 2.1.2
- Algolia Client Version: #.#.#
- Language Version: ruby-2.7.4

### Description

It looks like `algoliasearch-rails` creates a new instance of the `Algolia::Search::Client` using the `create_with_config` method.  The class takes options which include `opts[:logger]`, but the `create_with_config` method does not allow for passing of options, so the class defaults to using `LoggerHelper.create('debug.log')` for logging.  Our platform does not allow the gem to write to that file so we receive the following error: `No such file or directory @ rb_sysopen - debug.log (Errno::ENOENT)`.  

Logger Creation: 
https://github.com/algolia/algoliasearch-client-ruby/blob/20e8397f3a6826cf8288609a7d9158fa79027783/lib/algolia/search_client.rb#L22

Search Client Creation:
https://github.com/algolia/algoliasearch-rails/blob/0d152d33e5d028d785a0f5c17e9b5fcc48d609ed/lib/algoliasearch/configuration.rb#L27

### Steps To Reproduce

 * Run in environment where you cannot write to `./debug.log` file

**Comment by vhiairrassary** [comment]
We have the same issue. It seems https://github.com/algolia/algoliasearch-rails/pull/420 will fix it.

**Comment by cswilliams** [comment]
I also got bit by this issue after upgrading.  Will a new version of algoliasearch-rails be pushed to rubygems at some point?

**Comment by DevinCodes** [comment]
@cswilliams we'll release a new version on Monday! I think the `master` branch is production ready at this point, but we can't guarantee that's the case, so proceed at own risk 🙂
