### ISSUE TITLE
How to access attributesToSnippet from an activerecord object?

### ISSUE THREAD

**Issue by zenati** [algolia/algoliasearch-rails#42]
Hello,
```ruby
@records = Record.search(query, attributesToSnippet: ['content:50'])
```

In json result I can see `_snipet_result` attribute but how can I access it from `@record`?

https://github.com/zenati/algoliasearch-rails/commit/47faee39f987630d2ebe19628b4acd43b6e7bf1c

**Comment by redox** [comment]
Hey @zenati,

oh yes indeed this was missing. Even if most of our users are searching directly from the end-users' browsers (in JS) it make sense to have it in ruby as well. Also, if you don't need manipulate ActiveRecord objects, I recommend to use ```raw_search``` instead of ```search```.
