### ISSUE TITLE
Calling `.search` method without model

### ISSUE THREAD

**Issue by duhaime** [algolia/algoliasearch-rails#421]
We have two Rails apps that interact with Algolia. In app A we have a model Animals. We index that model from app A.

We'd then like to query the Animals index in Algolia serverside from app B, but app B doesn't have access to the Animals model, so we can't call `Animal.search()`. 

What's the best way to query our index serverside if the relevant model is not available? Any pointers would be hugely appreciated!

- rails version: 5.2.6.2
- algoliasearch-rails version: 1.24.1
- algoliasearch Version: 1.27.5
- ruby 2.6.8p205

**Comment by DevinCodes** [comment]
Hi @duhaime !

In that case, it's probably best to use the API client directly to target the index. Given the versions you mention, I think you should be able to do something like this in your code:

```ruby
index = AlgoliaSearch.client.init_index('animals') # replace with your index name
results = index.search('giraffe')
```

**Comment by duhaime** [comment]
Hi @DevinCodes, can this be reopened because with the versions I listed your snippet throws:

```
AlgoliaSearch.client
Traceback (most recent call last):
        1: from (irb):1
NoMethodError (undefined method `client' for AlgoliaSearch:Module)
```

**Comment by DevinCodes** [comment]
@duhaime and does `Algolia.client.init_index('animals')` work for you? This seems to work for me with the versions you provided, given that the Rails gem is [configured in an initializer](https://www.algolia.com/doc/framework-integration/rails/getting-started/setup/?client=ruby#global-configuration).

If this also doesn't work, I'd recommend setting up an instance of the API client as described in the [API client documentation](https://www.algolia.com/doc/api-client/getting-started/instantiate-client-index/ruby/?client=ruby).

**Comment by duhaime** [comment]
Ah mea culpa @DevinCodes, yes this works! 

I had read the error above too fast and thought `client` was not an attribute of `client` but in Ruby function calls have optional parentheses, so this was interpreted as a function call.

**Comment by DevinCodes** [comment]
Good to hear it works! Happy coding 😄

**Comment by duhaime** [comment]
@DevinCodes as it turns out, this seems not to support what I need. I want to call the `raw_search` method. Is that possible with the `Algolia` class?

**Comment by duhaime** [comment]
For others who end up here, I'm getting this done right now via:

```
class Animal < ApplicationRecord
  include AlgoliaSearch
  algoliasearch :index_name => "Animal_#{Rails.env}" do
  end
end
```
Then

`Animal.raw_search("yeet")`

But this is definitely a hack. If there's a better way I'm all for it.
