### ISSUE TITLE
Sager load associations through includes?

### ISSUE THREAD

**Issue by incorvia** [algolia/algoliasearch-rails#44]
Is there a way to eager load associations to loaded models?  I could theoretically index the data but then it seems I'd have to map my result set against the raw answer json to pull out the data I want which isn't that pretty..  Could easily do this if instead of returning an array Algolia Rails returned a scope..

**Comment by redox** [comment]
Not sure I got your point; when you say "loaded models", is that at search-time after using the `MyModel.search` method (loading results from your database)?

We generally recommend using `MyModel.raw_search` and deal directly with the JSON answer to avoid going through the database. You can also include the nested associated in your record like:

```ruby
class MyModel
  has_many :nested_objects

  include AlgoliaSearch
  algoliasearch do
    add_attribute :nested_objects do
      self.nested_objects.all.map { |o| { id: o.id, name: o.name } }
    end
  end
end
```

**Comment by incorvia** [comment]
Thanks, didn't know you recommend not going through AR.. I would like
Product.algolia_search('foo') to return a scope instead of an array so I
can chain off it if I want.. but short that I'll see what I can do with the
raw_search option.

On Mon, Mar 9, 2015 at 9:10 AM, Sylvain Utard <notifications@github.com>
wrote:

> Not sure I got your point; when you say "loaded models", is that at
> search-time after using the MyModel.search method (loading results from
> your database)?
>
> We generally recommend using MyModel.raw_search and deal directly with
> the JSON answer to avoid going through the database. You can also include
> the nested associated in your record like:
>
> class MyModel
>   has_many :nested_objects
>
>   include AlgoliaSearch
>   algoliasearch do
>     add_attribute :nested_objects do
>       self.nested_objects.all.map { |o| { id: o.id, name: o.name } }
>     end
>   endend
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/algolia/algoliasearch-rails/issues/44#issuecomment-77849910>
> .
>



-- 

Kevin

**Comment by redox** [comment]
Alright!

Yeah not going through the database is the more efficient in terms of performances. Also, if you're able to search directly from the JS code -> you'll reach the optimal performance :)

I'm closing this issue; feel free to re-open it if you have any issue :)
