### ISSUE TITLE
Problem with remaining records at the end of paginated collection

### ISSUE THREAD

**Issue by jeperkins4** [algolia/algoliasearch-rails#445]
- Rails version: Rails 6.1.7.3
- Algolia Rails integration version: algoliasearch-rails-2.3.2
- Algolia Client Version: NA
- Language Version: English

### Description
Paginated records clips off the last or remaining set of records beyond what is set in hitPerPage

### Steps To Reproduce
From Rails console... 
```
3.1.3 :027 > raw = Activity.search('*', { filters: "category:community", clickAnalytics: true,  page: 20, hitsPerPage: 50 }).raw_answ
er
 => 
{"hits"=>
... 
3.1.3 :027 > raw['hits'].count
 => 50 
3.1.3 :028 > raw['nbHits']
 => 1031 
3.1.3 :029 > raw = Activity.search('*', { filters: "category:community", clickAnalytics: true,  page: 21, hitsPerPage: 50 }).raw_answ
er
 => 
{"hits"=>[],
```

**Comment by jeperkins4** [comment]
Tried another experiment...
```
raw = Activity.search('*', { filters: "category:community", clickAnalytics: true,  page: 1, hitsPerPage: 1031 }).raw_ans
wer
 => 
{"hits"=>
... 
3.1.3 :006 > raw['hits'].count
 => 1000 
```
Looks like there might be a hard limit

**Comment by jeperkins4** [comment]
Looks like this limit is hard coded 
`DEFAULT_BATCH_SIZE = 1000`

**Comment by DevinCodes** [comment]
Hey @jeperkins4 !

The 1000 hits is a limitation of the search endpoint, please [see the docs](https://www.algolia.com/doc/api-reference/api-methods/search/). If you want to loop over more than 1000 items, you can use [browse](https://www.algolia.com/doc/api-reference/api-methods/browse/) instead. Hope this helps! 😄
