### ISSUE TITLE
Atomic reindex creates tmp index with empty setting

### ISSUE THREAD

**Issue by metheglin** [algolia/algoliasearch-rails#455]
- Rails version: 7.0.2
- Algolia Rails integration version: 3.0.0
- Algolia Client Version: 3.7.1
- Language Version:

### Description

Atomic reindex (ex: Product.reindex) is always going to create tmp index with empty setting when `check_settings=true`. When index move completed, previous settings disappeared. Not only specified settings inside algoliasearch block, but manual setting on dashboard.

When `check_settings=false` this problem seems not happening.  
When `check_settings=true`, after task done the settings of new index is always empty even though settings(customRanking,searchableAttributes,...) described in algoliasearch block (See Step to Reproduce).

By the way, I executed `set_settings` command manually with my setting like below and it does work. So I guess it happens because `algolia_ensure_init` missed when `check_settings=true`.

```
resp = AlgoliaSearch.client.set_settings(
  'Product_development', 
  Algolia::Search::IndexSettings.new({
    "searchable_attributes"=>["fulltext_search"],
    "custom_ranking"=>["desc(updated_at_i)"],
    "replicas"=>["Product_price_asc_development", "Product_price_desc_development"]
  })
)
```

Please check PR for better understanding. https://github.com/algolia/algoliasearch-rails/pull/453

### Steps To Reproduce

`app/models/product.rb`

```
class Product < ApplicationRecord
  algoliasearch check_settings: true do
    attribute :title
    attribute :content
    attribute :updated_at_i
    
    customRanking ['desc(updated_at_i)']
    searchableAttributes ['title']
    indexLanguages ['ja']
  end
end
```

in rails console for instance

```
Product.reindex
  # Check dashboard, all specified settings are disappeared.
  # Not only specified settings inside algoliasearch block, but manual setting on dashboard.
```

**Comment by DevinCodes** [comment]
This is fixed with https://github.com/algolia/algoliasearch-rails/pull/453, and released in v3.0.1. Thank you for the contribution 🙇‍♂️
