### ISSUE TITLE
Prefix or Suffix environment name of indices?

### ISSUE THREAD

**Issue by chibicode** [algolia/algoliasearch-rails#49]
On the website, it says to prefix your index with an environment name:

![image](https://cloud.githubusercontent.com/assets/992008/7175771/28b201fa-e3cd-11e4-9698-3cbcf39c3323.png)

But the README says to suffix it:

![image](https://cloud.githubusercontent.com/assets/992008/7175778/3abca6fc-e3cd-11e4-8742-7b6fa90b4a3b.png)

I'm guessing that the website is incorrect?

**Comment by redox** [comment]
Hi @chibicode,

oh it's actually a best practice more than a rule: both are OK. In Rails, the "per_environment" option will suffix your index name by the environment. I'll patch the website to put prefix/suffix instead of just prefix.

Thank you!

**Comment by chibicode** [comment]
Thanks!
