### ISSUE TITLE
Leverage the new ActiveJob or any queueing system

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-rails#52]
All indexing tasks should be done through ActiveJob if Rails >= 4.2

**Comment by wellinformed** [comment]
FWIW we're now running this is production. Will feedback how it goes. Thanks!

The only issue I can imagine is several updates running out of order. Not sure that Delayed Job can guarantee the order in which jobs are run.

**Comment by redox** [comment]
Alright, thank for for the feedback @wellinformed. Indeed I'm not sure ordering can be conserved whatever the queuing system.
