### ISSUE TITLE
WebMock globally disabled in gem

### ISSUE THREAD

**Issue by michaelnatkin** [algolia/algoliasearch-rails#57]
Using 

```require 'algolia/webmock'```

internally does

```
# disable by default
WebMock.disable!
```
which is rude behavior in a project that is already using WebMock for other things. It should just set up the stubs but leave it to the client rails app to decide when to enable or disable, either globally or with specific parameters.

**Comment by redox** [comment]
Yes, right; that's not very smart. I've just fixed it in the underlying Ruby API client (https://github.com/algolia/algoliasearch-client-ruby/commit/fafed102c5d855893cfca6a323c027e59810a248) and I'll publish a `1.4.3` version removing it. You can just for `gem "algoliasearch", "~> 1.4.3"` in your `Gemfile` to pull the latest version.

**Comment by michaelnatkin** [comment]
Awesome, thanks for the quick fix!
