### ISSUE TITLE
Displaying number of hits in header template

### ISSUE THREAD

**Issue by ashwinphatak** [algolia/algoliasearch-rails#58]
When displaying a header for each category in a multi-category (multi index) search, how can we display the total number of hits?

The header template context doesn't seem to have this info?

**Comment by ashwinphatak** [comment]
Should have included some more context: I'm talking about displaying matches in a dropdown using the typeahead JS library.

**Comment by redox** [comment]
Hi @ashwinphatak,

indeed Twitter's typeahead.js doesn't provide any way to do that. We're still thinking about building our own auto-completion menu library instead of depending on typeahead.js... but that's a big project :/ That's definitely something we would include.

**Comment by ashwinphatak** [comment]
https://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js

The latest version seems to have additional context data, but it doesn't seem to work as a drop-in replacement. 

```
            _getHeader: function getHeader(query, suggestions) {
                return this.templates.header ? this.templates.header({
                    query: query,
                    suggestions: suggestions,
                    dataset: this.name
                }) : null;
            },
```

**Comment by redox** [comment]
OK interesting, I will give it a try. The issue with the 1.11 version is that it's totally broken with remote sources (https://github.com/twitter/typeahead.js/issues/1185) and Twitter doesn't fix it :/

**Comment by ashwinphatak** [comment]
Ah, that explains. Thanks.
