### ISSUE TITLE
Environment variable for disable_indexing

### ISSUE THREAD

**Issue by purban** [algolia/algoliasearch-rails#63]
Let's allow the disable_indexing option to be set by an environment variable, so that we can add one line inside the config/environments/test file instead of updating all Models including Algolia.

**Comment by redox** [comment]
I propose to add it at the initialization step:

```ruby
AlgoliaSearch.configuration = { application_id: 'YourApplicationID', api_key: 'YourAPIKey', disable_indexing: Rails.env.test? }
```

**Comment by muichkine** [comment]
+1. Is this supported by current gem version?

**Comment by redox** [comment]
Right now it's not available as a configuration key, but you can for instance use the mechanism we use for testing: https://github.com/algolia/algoliasearch-rails#note-on-testing

**Comment by redox** [comment]
Keep only #85
