### ISSUE TITLE
Multiple indexes on the same model

### ISSUE THREAD

**Issue by nishantmodak** [algolia/algoliasearch-rails#64]
For a model, can there be multiple indexes on the same model?

Doing that, doesn't seem to work. Only 1 index is updated on doing a reindex

**Comment by ThomasBush** [comment]
@nishantmodak I just came across the same issue and realized I missed it in the [docs here](https://github.com/algolia/algoliasearch-rails#target-multiple-indexes).

You want to nest the second index inside the first index call changing from a second "algoliasearch" to "add_index" method.  

Also, if like me you were naming the index specifically like this: 
    ```add_index index_name: "model#{Rails.env}", auto_index: false, if: :open? do```

Be sure to **remove** ```index_name:``` as this (I believe) is the expected first parameter of ```add_index```.   If you don't it will throw an encoding Hash error.

**Resulting in:**
 ```add_index "model#{Rails.env}", auto_index: false, if: :open? do``` 

Hope this helps!
