### ISSUE TITLE
Potential enhancement for custom attribute definition

### ISSUE THREAD

**Issue by chrisyeung1121** [algolia/algoliasearch-rails#66]
I was working on some custom attributes and ended up had to write a few methods like the following:

``` ruby
def custom_attribute_changed?
  self.attribute_a_changed? || self.attribute_b_changed?
end

def custom_attribute_2_changed?
  self.attribute_c_changed? || self.attribute_d_changed?
end
```

I did some little experiments and found out that whenever anything changed (including nested object / associations), `updated_at` will always change when you call `record.save!`. I guess we can just use one method to trigger `index!` everytime instead of having to write `_changed?` method for all custom attributes?

``` ruby
	def updated_at_i_changed?
		self.updated_at_changed?
	end
```

**Comment by redox** [comment]
Definitely, you can do that.

The idea of creating 1 method per attribute is more to be able to NOT trigger the indexing in case you update your record but none of the attributes you're updating are configured to be sent to Algolia (so the `updated_at` attribute would changed but all other attributes sent to Algolia wouldn't).

But that's definitely an option if you index all attributes or if you update only attributes that are indexed.
