### ISSUE TITLE
undefined method `tags' for AlgoliaSearch

### ISSUE THREAD

**Issue by tmilewski** [algolia/algoliasearch-rails#67]
I have the following code in my `User` class:

```ruby 
include AlgoliaSearch
algoliasearch enqueue: true, per_environment: true, if: :index_on_algolia?, disable_indexing: Rails.env.test? do
  attribute :name, :email, :follower_count, :post_count
  customRanking ['desc(follower_count)', 'desc(post_count)']
  tags [:institution_id]
end
```

Every time I try to start `rails c` or `rails s` up, I'm greeted with `undefined method 'tags' for #<AlgoliaSearch::IndexOptions ...`

Any ideas?

**Comment by redox** [comment]
That's weird; can you confirm the version of the `algoliasearch-rails` gem you're using?

**Comment by tmilewski** [comment]
Well, just found an issue in RubyGems via a typo...

<img width="578" alt="screen shot 2015-07-30 at 10 04 53 am" src="https://cloud.githubusercontent.com/assets/26691/8985001/0dc40cca-36a3-11e5-9d79-dfdf13e6df33.png">

<img width="315" alt="screen shot 2015-07-30 at 10 04 13 am" src="https://cloud.githubusercontent.com/assets/26691/8984993/052c8e3e-36a3-11e5-950b-e8a6c5cfbf63.png">

The gem worked, but to a point. Will try it out with another release.

**Comment by tmilewski** [comment]
Color me confused:

<img width="640" alt="screen shot 2015-07-30 at 10 12 55 am" src="https://cloud.githubusercontent.com/assets/26691/8985127/b4514e0e-36a3-11e5-89e6-2806f3965b1b.png">

**Comment by tmilewski** [comment]
That worked. I have no idea what it was pulling. It still partially worked.

Regardless, it's a RubyGems issue.

Thanks!

**Comment by redox** [comment]
Oh I see :) good catch!
