### ISSUE TITLE
Trigger reindexation after counter_cache updated

### ISSUE THREAD

**Issue by chrisyeung1121** [algolia/algoliasearch-rails#68]
I have a Car model:

```ruby
class Car < ActiveRecord::Base
  has_one :price
  has_many :car_favourites, dependent: :destroy
  include AlgoliaSearch
  algoliasearch do
    attribute :favourite_count
    attribute :updated_at_i do
      updated_at.to_i
    end
  end
  def updated_at_i_changed?
    self.updated_at_changed?
  end
end
```

and a CarFavourite Model

```ruby
class CarFavourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :car, counter_cache: :favourite_count
end
```

I used a `updated_at_i` to trigger reindexation whenever _anything_ changed in the record, including the associations, like `car -> has_one :price`, `accepts_nested_attributes_for :price`. 

I found out that when `counter_cache` is updated, it doesn't really cause an reindexation, I wonder how you guys would solve this?

**Comment by bobylito** [comment]
Thanks for the issue. We're looking at it :)

**Comment by bobylito** [comment]
OK so it seems like the `counter_cache` attribute does not trigger the update via dirty checking (updated_at_i_changed?). I think that this article might give some information on this specific issue and how to solve it : http://stackoverflow.com/a/9407186

**Comment by chrisyeung1121** [comment]
I guess it's more of a rails issue than algolia's issue then, for those who are looking for a solution. 

```ruby
        before_save :increment_counter_cache
	before_destroy :decrement_counter_cache

	validates_uniqueness_of :car_id, :scope => :user_id

	# validates_uniquness_of :car_id, scope: :user_id

	private

	def increment_counter_cache
		Car.find(self.car_id).update_attribute(:updated_at, Time.now)
	end

	def decrement_counter_cache
		Car.find(self.car_id).update_attribute(:updated_at, Time.now)
	end
```

**Comment by bobylito** [comment]
I guess so too :) Closing the issue :)

**Comment by redox** [comment]
:+1:
