### ISSUE TITLE
Gem does not respect ActiveJob prefixing

### ISSUE THREAD

**Issue by creeonix** [algolia/algoliasearch-rails#69]
I am using SQS for background job processing, it is very sensitive to queue name.
ActiveJob has very good feature - ability to prefix `queue_name`. Since code to define background job class placed in `lib/algoliasearch-rails.rb` which is included before initialization, `queue_name` is not set properly.

I did quick hack, more permanent solution should be moving out job declaration of `AlgoliaSearch::AlgoliaJob` somewhere else... or lazy load

`application.rb`
```ruby
    config.active_job.queue_adapter = :shoryuken
    config.active_job.queue_name_prefix = Rails.env
    config.active_job.queue_name_delimiter = '_'
```

Hack:
`app/jobs/algolia_search/algolia_job.rb`
```ruby
AlgoliaSearch.send(:remove_const, :AlgoliaJob)
class AlgoliaSearch::AlgoliaJob < ::ActiveJob::Base
  queue_as :algoliasearch

  def perform(record, method)
    record.send(method)
  end
end
```

**Comment by redox** [comment]
Thanks for reporting that @creeonix, very clear. I'll check what other libraries are doing to handle that case, any chance you know one?

**Comment by redox** [comment]
Should we go for `autoload` so we can lazy load the job?

**Comment by redox** [comment]
@creeonix could you try with the master branch and tell me if it's working, I'll then bump the version & publish the gem.

**Comment by creeonix** [comment]
autoload needs second argument
```
irb(main):001:0> AlgoliaSearch::AlgoliaJob
LoadError: cannot load such file -- algolia_search/algolia_job
```

**Comment by redox** [comment]
Good catch, sorry for that; I'm on it

**Comment by creeonix** [comment]
And it works as expected now. Thanks!

**Comment by redox** [comment]
Alright, let me bump the version and publish then! Thanks for you help @creeonix

**Comment by redox** [comment]
It's part of `1.13.2` @creeonix, thanks for the help!

**Comment by tmilewski** [comment]
@redox `LoadError: cannot load such file -- algolia_search/algolia_job` still seems to be an issue on `1.13.2` for @rmfarrell and I. `1.31.1` is working perfectly.

**Comment by redox** [comment]
@tmilewski that's weird; could you provide me the whole backtrace to ensure it's related to the `autoload`?

**Comment by creeonix** [comment]
@redox you forgot to include `algolia_job.rb` into commit

**Comment by redox** [comment]
oh god, thanks @creeonix; fixing that now @tmilewski

**Comment by creeonix** [comment]
works - all tests passing now

**Comment by redox** [comment]
:+1:

**Comment by tmilewski** [comment]
@redox @creeonix Awesome! Thanks to the both of you!
