### ISSUE TITLE
Integrate with ActiveModel::Serializer

### ISSUE THREAD

**Issue by jamesfzhang** [algolia/algoliasearch-rails#70]
I think it's a fairly common use-case where you want Algolia search results to follow the same structure as the JSON responses from the application's API. One of the most popular ways to render JSON is to use [AMS](https://github.com/rails-api/active_model_serializers). Rather than having to define a serializer for an object as well as the `algoliasearch` block, it would be great if Algolia can utilize the object's serializer directly. This would also simplify dealing with models that have any `has_*` relationships.

**Comment by redox** [comment]
:+1: 

What do you propose in terms of API @jamesfzhang? Also, how would you deal with nested relations?

**Comment by jamesfzhang** [comment]
I'm thinking something along the lines of this:

```ruby
# post_serializer.rb
class PostSerializer < ActiveModel::Serializer
  attributes :id, :title, :text
  has_one :author
  has_many :comments
end

# author_serializer.rb
class AuthorSerializer < ActiveModel::Serializer
  attributes :id, :name
end

# comment_serializer.rb
class CommentSerializer < ActiveModel::Serializer
  attributes :text
  has_one :author
end

# post.rb

algoliasearch do
  use_serializer PostSerializer
end
```

would be equivalent to

```ruby
algoliasearch do
  attribute :id, :title, :text
  attribute :author do
    {
      id: author.id,
      name: author.name
    }
  end
  attribute :comments do
    comments.map do |comment|
      {
        text: comment.text,
        author: comment.author.as_json
      }
  end
end
```

Behind the scenes, maybe the `use_serializer` method should operate like this:

1. Call `PostSerializer.new` using the instance.
2. Call `.as_json` on the serialized instance, and set each key value pair as attributes for Algolia.

Not sure about how updates to an associated object should result in re-indexing the object.

**Comment by muichkine** [comment]
+1, we're also spending efforts to have both algolia and activemodel serializers return the same data. Having one and only way would reduce the burden and avoid discrepancies.

**Comment by redox** [comment]
:+1:

**Comment by muichkine** [comment]
Buy the way, we will migrate our rendering system (which currently uses jbuilder) to `ActiveModel::Serializer` when Rails 5 is out since it is much faster and will be the default for Rails 5 apps. 

If we could also refactor the algolia attributes at the same time would just be super uber cool. :)

**Comment by yanismydj** [comment]
Just chiming it to say I'd love to see this happen!

**Comment by redox** [comment]
> Just chiming it to say I'd love to see this happen!

Trying something :)

**Comment by Apokly** [comment]
Any update on that ? :)
