### ISSUE TITLE
How to keep DRY for multiple indices for a model

### ISSUE THREAD

**Issue by chrisyeung1121** [algolia/algoliasearch-rails#72]
I plan to have a `public_index` and a `secured_index` one used by public and one for admin backend. I followed the tutorial and found out I can achieve it by 

``` ruby
algoliasearch index_name: SECURED_INDEX_NAME, id: :a, force_utf8_encoding: true, enqueue: :trigger_algolia_worker, raise_on_failure: Rails.env.development? do
  synonyms SYNONYM_DICTIONARY
  attribute :a, :b, :c, :d, :e, :f
  attribute :g do
    # some methods
  end
  attribute :h do
    # some methods
  end
  attribute :i do
    # some methods
  end

  add_slave 'slave_a' ...
  add_slave 'slave_b' ...
  add_slave 'slave_c' ...

  add_index PUBLIC_INDEX_NAME, if: :published?, id: :a, force_utf8_encoding: true, enqueue: :trigger_algolia_worker, raise_on_failure: Rails.env.development? do
    synonyms SYNONYM_DICTIONARY
    attribute :a, :b, :c, :d
    attribute :g do
      # some methods
    end

    add_slave 'slave_d' ...
    add_slave 'slave_e' ...
    add_slave 'slave_f' ...
  end
end
```

As seen from above, once complexity is introduced, a lot of the code is repeated, however, I am not too sure how to DRY is up. Any suggestions?

P.S. I have already taken first step to put `SYNONYM_DICTIONARY` as a constant so I don't repeat too much of that.

**Comment by chrisyeung1121** [comment]
May be do an extent where I can group attributes together like:

``` ruby
module CommonAttributes
   synonyms SYNONYM_DICTIONARY
    attribute :a, :b, :c, :d
    attribute :g do
      # some methods
    end
end
```

then I can do sth like

``` ruby
algoliasearch index_name: SECURED_INDEX do
  include CommonAttributes
  attribute :e, :f
  attribute :g do ... end
  attribute :h do ... end
  add_slave ..
  add_index index_name: PUBLIC_INDEX do
    include Common Attributes
    add_slave ..
  end
end 
```

**Comment by redox** [comment]
I think we should have implemented an implicit inheritance at the beginning. The slave or the extra index would then have every attribute/configuration defined by the parent index. But right now we cannot really change this behavior without breaking all existing implementation.

Maybe we could add an option? Something like:

```ruby
algoliasearch index_name: SECURED_INDEX do
  attribute :e, :f
  attribute :g do ... end
  attribute :h do ... end
  add_slave inherit: true do
    # override only what you need
  end
  add_index index_name: PUBLIC_INDEX, inherit: true do
    # override only what you need
  end
end 
```

Not sure about the wording :/ What do you think @chrisyeung1121 ?

**Comment by chrisyeung1121** [comment]
Great! I think `inherit: true` will solve most use cases, only breaking case I can think of now is when `PUBLIC_INDEX` may not want to inherit all from `SECURED_INDEX`, so there may need an option to negate from the ineheritance.

Correct me if I am wrong, the above architectured is needed because I can only scope the index within `add_index` but not from the parent one? i.e.

```ruby
algoliasearch index_name: SECURED_INDEX do
  # also search the hidden dataset
  add_index index_name: PUBLIC_INDEX, if: :published, inherit: true do
    # only search through the published scope
  end 
end
``` 
But not the other way, i.e.

``` ruby
algoliasearch index_name: PUBLIC_INDEX, if: :published do
  # already scoped to published
  add_index index_name: PUBLIC_INDEX, inherit: true do
    # [?] not able to index the hidden dataset
  end 
end
```

**Comment by muichkine** [comment]
+1

**Comment by yordis** [comment]
+1

**Comment by Jerskouille** [comment]
`inherit` was implemented in [1.18.0](https://github.com/algolia/algoliasearch-rails/blob/master/ChangeLog#L12) !

**Comment by duhaime** [comment]
@Jerska is there documentation on this `inherit` property?

**Comment by Jerska** [comment]
The option is a boolean, you'll actually find more examples in this issue than in the doc, but here is the only mention I found:
https://www.algolia.com/doc/framework-integration/rails/index-configuration/replicas-multiple-indices/?client=ruby#replicas
