### ISSUE TITLE
Detect changes in associations

### ISSUE THREAD

**Issue by chrisyeung1121** [algolia/algoliasearch-rails#74]
In the **nested object / assocation** section, 

I am wondering how to detect association changes and trigger reindex?

**Comment by redox** [comment]
Hey @chrisyeung1121,

currently there is not automatic way to do that, you need to call the `reindex!` method of the parent object yourself. One solution could be to implement the [after_touch](https://github.com/algolia/algoliasearch-rails/issues/40) issue.

Are you used to use the `touch` callbacks?

**Comment by chrisyeung1121** [comment]
I have used somethings like 

``` ruby 
class Car
  belongs_to :user, touch: true
end
``` 

in which when cars get updated, the `updated_at` in user will change. but not the inverse.. I guess in this case I can have a `after_touch` call back in the User model. I wonder if I should use `after_save` or `after_commit` or `after_touch` though

**Comment by matisoffn** [comment]
+1

**Comment by dodeja** [comment]
+1

**Comment by julienbourdeau** [comment]
If I understand correctly this was documented some time ago: https://www.algolia.com/doc/framework-integration/rails/options/#nested-objectsrelations

I think I can close this issue. If I missed something, please let me know and I'll reopen it.
