### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by omarshammas** [algolia/algoliasearch-rails#76]
I ran into difficulties with an older project where I would run an *add object* or *new index* commands and they would appear to go through from the console but in the algolia dashboard there were no changes. I figured it may just be taking some time because of algolia's asynchronous design when writing.

But that wasn't it. I tried to add an object via curl and it worked. I then wrote a quick ruby script to see if the underlying algoliasearch gem would work. It failed with an error `sslv3 alert handshake failure`.

Then I came across this issue which pointed me in the write direction. https://github.com/algolia/algoliasearch-rails-example/issues/4 Turns out it required a particular version of the `httpclient` gem.

It shouldn't have taken me this long to figure out the problem. I know we don't want to throw an error after saving when calling `index!` because we don't want to break the application in production just to update the index but there should be a way to debug these types of errors and pinpoint where it is failing especially in development.

**Comment by redox** [comment]
This has been fixed with the `raise_on_failure` option: https://github.com/algolia/algoliasearch-rails#exceptions
