### ISSUE TITLE
Auto-remove & background jobs: cannot load model from DB

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-rails#77]
If you're using the queue system, the model won't load from the database in the background job if it has been removed. We should serialize the objectID and not the full object.

**Comment by chrisyeung1121** [comment]
I was gonna ask something about this. What should I do to update the index if I delete a record and I am using the queue system? I can't seem to remove record from index after it's deleted in database.

**Comment by redox** [comment]
Need to fix #75
