### ISSUE TITLE
Model.search clashes with Ransack methods

### ISSUE THREAD

**Issue by muichkine** [algolia/algoliasearch-rails#80]
Hello, the `search` method is already used by Ransack (https://github.com/activerecord-hackery/ransack):

    [28] pry(main)> Transaction.method(:search).source_location
    => ["/home/muichkine/.rvm/gems/ruby-2.2.2/gems/ransack-1.7.0/lib/ransack/adapters/mongoid/base.rb", 44]
    [29] pry(main)> Transaction.method(:raw_search).source_location
    => ["/home/muichkine/.rvm/gems/ruby-2.2.2/gems/algoliasearch-rails-1.14.1/lib/algoliasearch-rails.rb", 525]

A lot of other gems depend on ransack, like (for my case, active_admin).

Cheers.

**Comment by redox** [comment]
@muichkine every method added by the gem is prefixed by `algolia_` and alias to its short version if there is no conflict.

I recommend you to include the `AlgoliaSearch` module **after** Ransack and use `Transation.algolia_search`.

I'm closing the issue, but let me know if that doesn't work for you!

**Comment by muichkine** [comment]
OK, thx.
