### ISSUE TITLE
Error raised despite conditional returning not to index

### ISSUE THREAD

**Issue by muichkine** [algolia/algoliasearch-rails#81]
Hello,

   It's a corner case but as it is a pain to track, I'm posting it here if anyone is willing to fix.

  I have 

    algoliasearch index_name: 'transaction', id: :algolia_first_id, :if => :algolia_first_present?, per_environment: true do
       #whatever
    end

`:algolia_first` is a method that contains some logic that may return `nil`. That is why I added the conditional `:if => :algolia_first_present?` to not index when there is no algolia_first_id.

That code here still throws an error: `ArgumentError: Cannot index a blank objectID`. This feels counter intuitive. 

I went around by having the `:algolia_first_id` always return something, even though it's useless.

**Comment by redox** [comment]
Hi @muichkine, thank you for the bug report. Indeed as soon as you add the `if:` constraint, we also send "DELETE" operations at save (when the condition returns `false`). In such case, we probably just want to skip the DELETE, I'll fix it.

**Comment by redox** [comment]
Hey @muichkine, do you mind giving a try to the `master` branch?

**Comment by muichkine** [comment]
Hello @redox , sorry for the silence, I haven't had time to test with master. I'll let you know when I can. :) Thanks for the push.

**Comment by redox** [comment]
:+1: @muichkine
