### ISSUE TITLE
Index name capitalized

### ISSUE THREAD

**Issue by muichkine** [algolia/algoliasearch-rails#83]
I have

    class Item
      include Mongoid::Document
      algoliasearch :index => 'item', :per_environment => true do
        # whatever
      end
    end

for some reason, the index name as seen on the website and as queryable from the front client has a capitalized name ("Item_production" for instance). Our old (before today) indexes all have lower case names.

I can't track back where this went wrong but since I reinstalled my whole system, I guess I updated the algoliasearch-rails gem. Since Item is the only index I created since then I suspect this is coming from the update.

Its pretty annoying since we have in our rails models only lower case names for indexes and in production it's sometimes capitalize, sometimes lowercase.

I also suspect this to be tied to https://github.com/algolia/algoliasearch-rails/issues/82

**Comment by redox** [comment]
The default name is indeed based on the model name (so Capitalized). Not sure why it bypassed your `:index => 'item'` option; any chance it was the same cause than #82? Closing it for now, please re-open if there is still a bug.
