### ISSUE TITLE
Can't remove_from_index after destroying from console

### ISSUE THREAD

**Issue by chrisyeung1121** [algolia/algoliasearch-rails#87]
``` ruby
module Algolia
    class RequestIndexWorker
        include Sidekiq::Worker
        sidekiq_options :retry => false, :queue => :algolia

        # use .destroy rather than .delete if you want to trigger remove_from_index! method

        def perform(reference, remove)
            r = Request.find_by_reference(reference)
            remove ? r.remove_from_index! : r.index!
        end

    end
end
```

And whenever I do `destroy` in console it will have an error message

2015-10-27T09:09:33.432Z 71962 TID-owwqrc480 WARN: undefined method `remove_from_index!' for nil:NilClass

i assume basically the record is already deleted?

**Comment by chrisyeung1121** [comment]
I did more testing and it seems the behaviour is indeterministic. 

First time i did `Car.last.destroy`. The result is as below:

```shell
18:16:20 worker.1 | 2015-10-27T10:16:20.534Z 71962 TID-owwqrc480 WARN: {"retry"=>false, "queue"=>"algolia", "class"=>"Algolia::CarIndexWorker", "args"=>["citroen-tseuto-2015-1446", true], "jid"=>"bbfdfd069bfbc7d6db170fe2", "enqueued_at"=>1445940980.530058}
18:16:20 worker.1 | 2015-10-27T10:16:20.534Z 71962 TID-owwqrc480 WARN: undefined method `remove_from_index!' for nil:NilClass
```

Second time I did `Car.last.destroy`

```
18:16:41 worker.1 | 2015-10-27T10:16:41.736Z 71962 TID-owwqrc480 Algolia::CarIndexWorker JID-8b5151ee920aab2cfb8420ed INFO: start
18:16:41 worker.1 | 2015-10-27T10:16:41.818Z 71962 TID-owwqrc480 Algolia::CarIndexWorker JID-8b5151ee920aab2cfb8420ed INFO: done: 0.083 sec
```

Checking the index, it concurs with the error that the second record was deleted while the first one is still here. 

Any thoughts?

**Comment by duboff** [comment]
Same problem. There should be a way to remove from index by id only, not through the fetching the record.

**Comment by bitxpert** [comment]
Same problem, any solutions?

If i use enqueue, i always get exception because it tries to load user after it has been deleted. Some method to remove from index only providing id is needed to solve the issue. Instead of relying on whole object retrieval and calling remove_from_index! on that object.

**Comment by duboff** [comment]
Hi @bitxpert, we've ended up overriding the default index job with the something like this (I removed a bit of the code from this snippet, but should still work):

```
class AlgoliaIndexJob < ActiveJob::Base		
  include Rollbar::ActiveJob		
 		
  queue_as :algoliasearch		
 		
  def perform(id, remove)		
    index = Algolia::Index.new("index_name")		
 		
    if remove		
      index.delete_object(id)		
    else		
      response = Response.find(id)		
      settings = Response.algoliasearch_settings		
 	
      index.add_object(settings.get_attributes(response), id)
    end		
  end		
end
```

**Comment by redox** [comment]
Indeed, the job will be called after the object has been removed... We need to work on a fix; in the meantime, what about a mix of all those answers:

```ruby
module Algolia
    class RequestIndexWorker
        include Sidekiq::Worker
        sidekiq_options :retry => false, :queue => :algolia

        def perform(id, remove)
           if remove
             ## Cannot use MyModel.find, the object has been deleted
             raw_index = Algolia::Index.new(MyModel.index.name)
             raw_index.delete_object(id)
           else
             MyModel.find(id).index!
           end
        end

    end
end
```

Let me know if that makes sense

**Comment by Spone** [comment]
Will you release a new version with a fix for this bug?
