### ISSUE TITLE
New account ID doesn't resolve correctly

### ISSUE THREAD

**Issue by ekampp** [algolia/algoliasearch-rails#89]
I recently created an account with Algolia, and added the rails gem. 

The URL that the initial import tried to access was a subdomain named as my ID. This failed to resolve and I was unable to communicate with Algolia in any way. 

Let me know, if you need more details. I removed the gem from my project again, so I don't have the specifics at hand, but I can get at them in needed.

**Comment by redox** [comment]
Hey @ekampp,

it should be OK now; we had some lag on the DNS creations -> sorry about that. Let me know if that works you!
