### ISSUE TITLE
Gem checks `_geoloc_changed?` instead of geoloc attributes

### ISSUE THREAD

**Issue by olance** [algolia/algoliasearch-rails#91]
When using `geoloc :lat, :lng`, the `must_index?` method does not check for `lat_changed?`/`lng_changed?` on an updated record, but for the private attribute `_geoloc`, which is not intuitive and can cause operations to be sent to Algolia when nothing has actually changed

**Comment by julienbourdeau** [comment]
👋 Thank you @olance 

I added a section in the documentation about `geoloc` and `tags`helpers. The temporary doc is here and should be released very soon: https://deploy-preview-2711--algolia-doc.netlify.com/doc/framework-integration/rails/indexing/indexing/?language=php#tags-and-geoloc-helpers

**Comment by olance** [comment]
Hey @julienbourdeau 🙂 

Thanks for the update! I love the new docs btw 😍 

Just one thing: the docs say "Notice the double underscores" but I couldn't see any in the provided code!

**Comment by julienbourdeau** [comment]
![Screenshot 2019-03-21 at 14 50 25](https://user-images.githubusercontent.com/1525636/54756547-bef90f00-4be8-11e9-863c-898d8512042f.png)

I thought it would be clear enough, I'll see if I can find something clearer 👍 Thanks!

**Comment by olance** [comment]
Oh yeah, okay!

Maybe something like this:
![image](https://user-images.githubusercontent.com/314079/55078434-73d47580-509a-11e9-837e-eb18cb9ae2b5.png)
?

**Comment by julienbourdeau** [comment]
Sold! I'll update the doc

**Comment by olance** [comment]
(funny that I created this issue right after I joined Algolia, and it got solved right after I left 😛)
