### ISSUE TITLE
enqueue argument not doing anything

### ISSUE THREAD

**Issue by biznickman** [algolia/algoliasearch-rails#93]
Here's my configuration within my ActiveModel object:

    algoliasearch if: :published?, enqueue: :trigger_index_worker, per_environment: true do
      # list of attribute used to build an Algolia record
      attributes :id, :title, :description, :status
    end

    def published?
      (status == 'published')
    end

    def self.trigger_index_worker record, remove
      puts "trigger index was called"
      AlogliaSearchJob.perform_async(record.id, remove)
    end

`self.trigger_index_worker` is never called in this system. I'm currently using it in my development environment and am using a Sidekiq active job worker to process the indexing. It's happening synchronously though. 

Am I missing something here?

It would also be useful to make synchronous an environment dependent setting. In testing synchronous should be enforced.

**Comment by biznickman** [comment]
I believe I just resolved the issue. This background process does not occur when calling `Model.reindex!` only on individual objects.

**Comment by redox** [comment]
Hey @biznickman, sorry for not replying earlier; that occurred during my vacations :sunglasses:

> I believe I just resolved the issue. This background process does not occur when calling Model.reindex! only on individual objects.

Yes correct :+1:
