### ISSUE TITLE
browse API support?

### ISSUE THREAD

**Issue by ashwinphatak** [algolia/algoliasearch-rails#94]
Does this gem support the browse API to fetch > 1000 records? (https://www.algolia.com/doc/faq/index-configuration/how-can-i-retrieve-all-the-records-in-my-index).

I'm using the rails Model.algolia_search method, not the JS library.

**Comment by redox** [comment]
Hi @ashwinphatak; the browse is part of the underlying `algoliasearch` gem (native Ruby API client); you can do something like:

```ruby
MyModel.index.browse do |hit|
  p hit
end
```

Let us know how that goes!
