### ISSUE TITLE
Searching encrypted data

### ISSUE THREAD

**Issue by mmahalwy** [algolia/algoliasearch-rails#96]
How can I search encrypted data that's been created by: https://github.com/attr-encrypted/attr_encrypted

**Comment by redox** [comment]
Sorry for the late reply. Unfortunately, typo-tolerant search engines are not designed to search inot encrypted data. The only thing you could do is push the encrypted string to Algolia and disable the typo-tolerance on that attribute + query the index with the encrypted version as well.
