### ISSUE TITLE
Search multiple indices?

### ISSUE THREAD

**Issue by mmahalwy** [algolia/algoliasearch-rails#97]
Is there a way to search multiple indices at the same time? I know this is possible in the frontend js solution

**Comment by Jerskouille** [comment]
You should have a look at the `algoliasearch` gem, which is used internally by this project.
As you can see in its documentation, you can search into muliple indices by using the `.multiple_queries` method: https://github.com/algolia/algoliasearch-client-ruby#multiple-queries  .
