### ISSUE TITLE
undefined method when using the unless: method option on algoliasearch definition in model

### ISSUE THREAD

**Issue by edalford11** [algolia/algoliasearch-rails#98]
I'm attempting to use the algoliasearch definition as follows:

```ruby
algoliasearch index_name: "Message", unless: self.filter_user_links, enqueue: :trigger_algolia_sidekiq_worker, per_environment: true do
```

But i'm getting an undefined method filter_user_links.

The method is defined below the block as follows:

```ruby
def filter_user_links
    @filter_user_links ||= filtered? || ((user.present? && user.filter_links?) && Message.extract_links(body).present?)
end
```

Using ruby 2.3.0 on Rails 3.2.22. Am I missing something here?

**Comment by kokliKo** [comment]
Hey @edalford11,

Can you try with this syntax:

```ruby
algoliasearch index_name: "Message", unless: :filter_user_link, ...
```

**Comment by edalford11** [comment]
yep I was definitely missing something. That works perfectly.

Also the :disable_indexing => Rails.env.test? doesn't seem to be working for me when it tries to make DELETE requests. It throws errors about the algolia api call not being stubbed. I included the WebMock.enable! before each test and that seems to work when running an individual test but when I run the whole model spec, it throws the same errors about the algolia api call not being stubbed only on DELETE requests..

**Comment by alexandremeunier** [comment]
Do you know where the DELETE requests are coming from in the `algoliasearch-rails` gem? Is it `#remove_from_index!` ? Any chance you could provide me with an example of test generating this request when `disable_indexing` should be false, so I can replicate it ? 

Regardless you should definitely be able to stub them using `WebMock`. Can you try adding 
```ruby
require 'algolia/webmock'
WebMock.enable!
``` 
to the top of your test file, and make sure that there is no call to `WebMock.disable!` somewhere that would be persisted across tests ?
